CREATE TABLE `directory_venues` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`country` text NOT NULL,
	`owner` text,
	`data` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`created` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `venue_claims` (
	`id` text PRIMARY KEY NOT NULL,
	`venue_id` text NOT NULL,
	`owner` text NOT NULL,
	`data` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`created` text NOT NULL,
	`reviewed_by` text,
	`reviewed_at` text,
	`reason` text
);
--> statement-breakpoint
ALTER TABLE `assets` ADD `purpose` text DEFAULT 'media' NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX venue_claim_pending_unique ON venue_claims(venue_id,owner) WHERE status='pending';
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-grand-prairie-stadium','ground','US','{"id":"us-grand-prairie-stadium","name":"Grand Prairie Cricket Stadium","kind":"ground","country":"US","state":"Texas","city":"Grand Prairie","address":"1600 Lone Star Parkway, Grand Prairie, TX 75050","latitude":null,"longitude":null,"level":"international","website":"https://www.visitgrandprairietx.com/Things-To-Do/Attractions/Major-League-Cricket-Stadium","sources":[{"url":"https://www.visitgrandprairietx.com/Things-To-Do/Attractions/Major-League-Cricket-Stadium","title":"Major League Cricket Stadium - Visit Grand Prairie"}],"description":"Cricket stadium used for Major League Cricket.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-church-street-park','ground','US','{"id":"us-church-street-park","name":"Church Street Park","kind":"ground","country":"US","state":"North Carolina","city":"Morrisville","address":"5817 Cricket Pitch Way, Morrisville, NC","latitude":null,"longitude":null,"level":"international","website":"https://www.morrisvillenc.gov/Things-To-Do/Professional-Cricket","sources":[{"url":"https://www.morrisvillenc.gov/Things-To-Do/Professional-Cricket","title":"Professional Cricket | Town of Morrisville"}],"description":"Town cricket venue that has hosted Major League Cricket.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-oakland-coliseum','ground','US','{"id":"us-oakland-coliseum","name":"Oakland Coliseum","kind":"ground","country":"US","state":"California","city":"Oakland","address":null,"latitude":null,"longitude":null,"level":"international","website":"https://www.majorleaguecricket.com/news/255","sources":[{"url":"https://www.majorleaguecricket.com/news/255","title":"Tickets for 2026 Season Now on Sale | MLC"}],"description":"Multipurpose stadium used for Major League Cricket in 2026.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-knight-riders-pomona','ground','US','{"id":"us-knight-riders-pomona","name":"Knight Riders Cricket Field","kind":"ground","country":"US","state":"California","city":"Pomona","address":null,"latitude":null,"longitude":null,"level":"international","website":"https://www.majorleaguecricket.com/news/255","sources":[{"url":"https://www.majorleaguecricket.com/news/255","title":"Tickets for 2026 Season Now on Sale | MLC"}],"description":"Cricket venue introduced in the 2026 Major League Cricket season.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-central-broward-stadium','ground','US','{"id":"us-central-broward-stadium","name":"Central Broward Park and Broward County Stadium","kind":"ground","country":"US","state":"Florida","city":"Lauderhill","address":"3700 NW 11th Place, Lauderhill, FL 33311","latitude":null,"longitude":null,"level":"international","website":"https://www.broward.org/Parks/Support/Documents/2026.05.01CBPOveriewPAB.pdf","sources":[{"url":"https://www.broward.org/Parks/Support/Documents/2026.05.01CBPOveriewPAB.pdf","title":"Central Broward Park Overview | Broward County"},{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"County cricket stadium with an international cricket history.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-marymoor-cricket','ground','US','{"id":"us-marymoor-cricket","name":"Marymoor Park Cricket Field","kind":"ground","country":"US","state":"Washington","city":"Redmond","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://cdn.kingcounty.gov/-/media/king-county/depts/dnrp/nature-recreation/parks-recreation/parks/marymoor/marymoor-special-events-guide-2024.pdf?hash=FD4873475E5ADE33514CB2AB12A9AC7F&rev=b310a617c6504ba78933160878c6e28d","sources":[{"url":"https://cdn.kingcounty.gov/-/media/king-county/depts/dnrp/nature-recreation/parks-recreation/parks/marymoor/marymoor-special-events-guide-2024.pdf?hash=FD4873475E5ADE33514CB2AB12A9AC7F&rev=b310a617c6504ba78933160878c6e28d","title":"Marymoor Special Events Guide | King County"}],"description":"Park cricket field with a permanent pitch.","amenities":["permanent pitch","restrooms","parking"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-lyon-oaks-cricket','ground','US','{"id":"us-lyon-oaks-cricket","name":"Lyon Oaks Cricket Ground","kind":"ground","country":"US","state":"Michigan","city":"Wixom","address":"52221 Pontiac Trail, Wixom, MI 48393","latitude":null,"longitude":null,"level":"club","website":"https://www.oakgov.com/home/showpublisheddocument/14409/638107718718270000","sources":[{"url":"https://www.oakgov.com/home/showpublisheddocument/14409/638107718718270000","title":"Park and Outdoor Recreation Investment Plan | Oakland County"}],"description":"County park with a cricket pitch.","amenities":["cricket pitch"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-van-cortlandt','ground','US','{"id":"us-van-cortlandt","name":"Van Cortlandt Park Cricket Fields","kind":"ground","country":"US","state":"New York","city":"Bronx","address":null,"latitude":null,"longitude":null,"level":"grassroots","website":"https://nycgovparks.org/parks/VanCortlandtPark","sources":[{"url":"https://nycgovparks.org/parks/VanCortlandtPark","title":"Van Cortlandt Park | NYC Parks"}],"description":"Public park with cricket fields.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-flushing-meadows','ground','US','{"id":"us-flushing-meadows","name":"Flushing Meadows Corona Park Cricket Fields","kind":"ground","country":"US","state":"New York","city":"Queens","address":null,"latitude":null,"longitude":null,"level":"grassroots","website":"https://nycgovparks.org/parks/flushing-meadows-corona-park","sources":[{"url":"https://nycgovparks.org/parks/flushing-meadows-corona-park","title":"Flushing Meadows Corona Park | NYC Parks"}],"description":"Public park offering cricket among its sports.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-marine-park','ground','US','{"id":"us-marine-park","name":"Marine Park Cricket Fields","kind":"ground","country":"US","state":"New York","city":"Brooklyn","address":"Flatbush, Gerritsen and Fillmore Avenues, Brooklyn, NY","latitude":null,"longitude":null,"level":"grassroots","website":"https://nycgovparks.org/parks/marine-park","sources":[{"url":"https://nycgovparks.org/parks/marine-park","title":"Marine Park | NYC Parks"}],"description":"Brooklyn park with cricket fields.","amenities":["restrooms"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-sam-houston','ground','US','{"id":"us-sam-houston","name":"Sam Houston Trail Park Cricket Field","kind":"ground","country":"US","state":"Texas","city":"Irving","address":"101 E. Interstate 635, Irving, TX","latitude":null,"longitude":null,"level":"grassroots","website":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","sources":[{"url":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","title":"New and Enhanced Cricket Fields | City of Irving"}],"description":"City cricket fields included in completed improvements.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-mountain-creek','ground','US','{"id":"us-mountain-creek","name":"Mountain Creek Preserve Cricket Field","kind":"ground","country":"US","state":"Texas","city":"Irving","address":"1005 E. Hunter Ferrell Road, Irving, TX","latitude":null,"longitude":null,"level":"grassroots","website":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","sources":[{"url":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","title":"New and Enhanced Cricket Fields | City of Irving"}],"description":"City cricket fields included in completed improvements.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-harrington','ground','US','{"id":"us-harrington","name":"W.O. Harrington Park Cricket Fields","kind":"ground","country":"US","state":"Texas","city":"Irving","address":"5350 Valley View Lane, Irving, TX","latitude":null,"longitude":null,"level":"grassroots","website":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","sources":[{"url":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","title":"New and Enhanced Cricket Fields | City of Irving"}],"description":"City cricket fields included in completed improvements.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-riverside-irving','ground','US','{"id":"us-riverside-irving","name":"Riverside Complex at Spring Trail Park","kind":"ground","country":"US","state":"Texas","city":"Irving","address":"Riverside Drive and Royal Lane, Irving, TX","latitude":null,"longitude":null,"level":"grassroots","website":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","sources":[{"url":"https://irvingtx.gov/index.php?project=143&projectsection=24&section=cip-parks-projects","title":"New and Enhanced Cricket Fields | City of Irving"}],"description":"City cricket fields included in completed improvements.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-miller-park','practice','US','{"id":"us-miller-park","name":"Albert C. Miller Park Practice Cricket Pitch","kind":"practice","country":"US","state":"Pennsylvania","city":"Exton","address":"220 Miller Way, Exton, PA 19341","latitude":null,"longitude":null,"level":"training","website":"https://www.westwhiteland.org/Facilities/Facility/Details/Albert-C-Miller-Park-1","sources":[{"url":"https://www.westwhiteland.org/Facilities/Facility/Details/Albert-C-Miller-Park-1","title":"Albert C. Miller Park | West Whiteland Township"}],"description":"Township park providing a practice cricket pitch.","amenities":["practice cricket pitch","parking","restrooms"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-exton-park','ground','US','{"id":"us-exton-park","name":"Exton Park Cricket Field","kind":"ground","country":"US","state":"Pennsylvania","city":"Exton","address":"200 Church Farm Lane, Exton, PA","latitude":null,"longitude":null,"level":"club","website":"https://www.westwhiteland.org/m/newsflash/Archive/Item/648?arcId=1345","sources":[{"url":"https://www.westwhiteland.org/m/newsflash/Archive/Item/648?arcId=1345","title":"Township Secures Park Grant | West Whiteland Township"}],"description":"Township multi-use fields include a cricket pitch.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-keney-park','ground','US','{"id":"us-keney-park","name":"Keney Park Cricket Field","kind":"ground","country":"US","state":"Connecticut","city":"Hartford","address":"337 Vine Street, Hartford, CT 06112","latitude":null,"longitude":null,"level":"club","website":"https://www.hartfordct.gov/Government/Departments/Public-Works/Parks-Directory","sources":[{"url":"https://www.hartfordct.gov/Government/Departments/Public-Works/Parks-Directory","title":"Parks Directory | City of Hartford"},{"url":"https://www.hartfordct.gov/files/assets/public/v/1/mayors-office/mayors-office-documents/mayor-bronin-sotc-3-27-23.pdf","title":"State of the City Address | City of Hartford"}],"description":"City park with an established cricket community.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-riverside-hartford','ground','US','{"id":"us-riverside-hartford","name":"Riverside Park Cricket Field","kind":"ground","country":"US","state":"Connecticut","city":"Hartford","address":"20 Leibert Road, Hartford, CT 06120","latitude":null,"longitude":null,"level":"grassroots","website":"https://www.hartfordct.gov/Government/Departments/Public-Works/Parks-Directory","sources":[{"url":"https://www.hartfordct.gov/Government/Departments/Public-Works/Parks-Directory","title":"Parks Directory | City of Hartford"}],"description":"Riverfront park with a cricket field.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-prairie-view','ground','US','{"id":"us-prairie-view","name":"Prairie View Cricket Complex","kind":"ground","country":"US","state":"Texas","city":"Prairie View","address":"Richards Road at Highway 290, Prairie View, TX 77445","latitude":null,"longitude":null,"level":"international","website":"https://pvcricketcomplex.com/","sources":[{"url":"https://pvcricketcomplex.com/","title":"Prairie View Cricket Complex"},{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"Cricket complex offering turf grounds and practice areas.","amenities":["turf wickets","practice areas"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-moosa-stadium','ground','US','{"id":"us-moosa-stadium","name":"Moosa Cricket Stadium","kind":"ground","country":"US","state":"Texas","city":"Pearland","address":"5515 McKeever Road #100, Pearland, TX 77584","latitude":null,"longitude":null,"level":"international","website":"https://mcs.moosastadium.com/","sources":[{"url":"https://mcs.moosastadium.com/","title":"Moosa Cricket Stadium"},{"url":"https://news.minorleaguecricket.com/2022/07/06/international-cricket-stars-to-feature-in-houston-cricket-festival-on-sunday-july-24/","title":"Houston Cricket Festival | Minor League Cricket"}],"description":"Private cricket stadium with match fields and practice pitches.","amenities":["floodlights","dressing rooms","showers","practice pitches"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-indoor-cricket-usa','academy','US','{"id":"us-indoor-cricket-usa","name":"Indoor Cricket USA","kind":"academy","country":"US","state":"New Jersey","city":"Whippany","address":"9 Whippany Road, Building C Unit 3, Whippany, NJ","latitude":null,"longitude":null,"level":"training","website":"https://indoorcricketusa.com/","sources":[{"url":"https://indoorcricketusa.com/","title":"Indoor Cricket USA"}],"description":"Indoor academy offering youth cricket coaching.","amenities":["indoor training"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-united-sports-arena','practice','US','{"id":"us-united-sports-arena","name":"United Sports Arena","kind":"practice","country":"US","state":"Massachusetts","city":"Franklin","address":"839 Upper Union Street, Franklin, MA 02038","latitude":null,"longitude":null,"level":"training","website":"https://www.unitedsportsarena.com/","sources":[{"url":"https://www.unitedsportsarena.com/","title":"United Sports Arena"},{"url":"https://www.unitedsportsarena.com/contact-us","title":"Contact Us | United Sports Arena"}],"description":"Indoor cricket facility offering coaching and lane rentals.","amenities":["indoor lanes","bowling machines","gym","pro shop"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-lords-indoor-sports','practice','US','{"id":"us-lords-indoor-sports","name":"Lords Indoor Sports","kind":"practice","country":"US","state":"Texas","city":"Plano","address":"2621 Summit Avenue, Suite 200, Plano, TX 75074","latitude":null,"longitude":null,"level":"training","website":"https://lordsindoorsports.com/","sources":[{"url":"https://lordsindoorsports.com/","title":"Lords Indoor Sports"}],"description":"Indoor cricket venue with training and court rentals.","amenities":["indoor fields","batting lanes","batting simulator"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-22yards-austin','practice','US','{"id":"us-22yards-austin","name":"22Yards Austin","kind":"practice","country":"US","state":"Texas","city":"Leander","address":"15905 Ronald Reagan Boulevard, Building 1, Leander, TX 78641","latitude":null,"longitude":null,"level":"training","website":"https://22yardsaustin.com/","sources":[{"url":"https://22yardsaustin.com/","title":"22Yards Austin"}],"description":"Indoor cricket venue offering lanes and coaching.","amenities":["indoor lanes","bowling machines"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-cricmax-old-bridge','academy','US','{"id":"us-cricmax-old-bridge","name":"CricMax Old Bridge","kind":"academy","country":"US","state":"New Jersey","city":"Old Bridge","address":"4440 Bordentown Avenue, Old Bridge, NJ 08857","latitude":null,"longitude":null,"level":"training","website":"https://cricmax.com/about-us/","sources":[{"url":"https://cricmax.com/about-us/","title":"About Us | CricMax"}],"description":"Cricket coaching location listed by CricMax.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-cricmax-cromwell','academy','US','{"id":"us-cricmax-cromwell","name":"CricMax ATI Cromwell","kind":"academy","country":"US","state":"Connecticut","city":"Cromwell","address":"14 Alcap Ridge, Cromwell, CT","latitude":null,"longitude":null,"level":"training","website":"https://cricmax.com/about-us/","sources":[{"url":"https://cricmax.com/about-us/","title":"About Us | CricMax"}],"description":"Cricket coaching location listed by CricMax.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-cricmax-south-windsor','academy','US','{"id":"us-cricmax-south-windsor","name":"CricMax South Windsor","kind":"academy","country":"US","state":"Connecticut","city":"South Windsor","address":"185 Commerce Way, South Windsor, CT","latitude":null,"longitude":null,"level":"training","website":"https://cricmax.com/about-us/","sources":[{"url":"https://cricmax.com/about-us/","title":"About Us | CricMax"}],"description":"Cricket coaching location listed by CricMax.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-dreamcricket-somerset','academy','US','{"id":"us-dreamcricket-somerset","name":"DreamCricket Academy Somerset","kind":"academy","country":"US","state":"New Jersey","city":"Somerset","address":"400 Apgar Drive, Suite K, Somerset, NJ 08873","latitude":null,"longitude":null,"level":"training","website":"https://www.dreamcricket.com/academy-home/","sources":[{"url":"https://www.dreamcricket.com/academy-home/","title":"DreamCricket Academy"}],"description":"Indoor academy with batting lanes and coaching.","amenities":["bowling machines","fitness center","pro shop","video analysis"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-pine-grove-manor','ground','US','{"id":"us-pine-grove-manor","name":"Pine Grove Manor Elementary School Cricket Ground","kind":"ground","country":"US","state":"New Jersey","city":"Somerset","address":"130 Highland Avenue, Somerset, NJ","latitude":null,"longitude":null,"level":"grassroots","website":"https://www.dreamcricket.com/academy-home/","sources":[{"url":"https://www.dreamcricket.com/academy-home/","title":"DreamCricket Academy"}],"description":"School ground identified as DreamCricket academy home ground.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-thunderbolts-academy','academy','US','{"id":"us-thunderbolts-academy","name":"Seattle Thunderbolts Cricket Academy","kind":"academy","country":"US","state":"Washington","city":"Redmond","address":"15320 NE 92nd Street, Redmond, WA 98052","latitude":null,"longitude":null,"level":"training","website":"https://www.thunderboltscricketacademy.com/","sources":[{"url":"https://www.thunderboltscricketacademy.com/","title":"Seattle Thunderbolts Cricket Academy"}],"description":"Redmond cricket academy offering training and lane rentals.","amenities":["indoor cricket"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-washington-cricket-academy','academy','US','{"id":"us-washington-cricket-academy","name":"Washington Cricket Academy","kind":"academy","country":"US","state":"Virginia","city":"Sterling","address":"21598 Atlantic Boulevard, Suite 130, Sterling, VA 20166","latitude":null,"longitude":null,"level":"training","website":"https://www.washingtoncricketacademy.org/contact-us","sources":[{"url":"https://www.washingtoncricketacademy.org/contact-us","title":"Contact Us | Washington Cricket Academy"}],"description":"Nonprofit academy supporting youth cricket in the DC region.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-master-strokes-katy','academy','US','{"id":"us-master-strokes-katy","name":"Master Strokes Cricket America - Cricbase USA Katy","kind":"academy","country":"US","state":"Texas","city":"Katy","address":"510 Mason Road, Suite S, Katy, TX 77450","latitude":null,"longitude":null,"level":"training","website":"https://www.mscacricket.com/","sources":[{"url":"https://www.mscacricket.com/","title":"Master Strokes Cricket America"}],"description":"Academy training location at Cricbase USA.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-hanover-park','ground','US','{"id":"us-hanover-park","name":"Hanover Park Cricket Ground","kind":"ground","country":"US","state":"Illinois","city":"Hanover Park","address":"1919 Walnut Avenue, Hanover Park, IL 60133","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-las-colinas-polo','ground','US','{"id":"us-las-colinas-polo","name":"Las Colinas Polo Grounds","kind":"ground","country":"US","state":"Texas","city":"Irving","address":"600 E Royal Lane, Irving, TX 75039","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-acac-park','ground','US','{"id":"us-acac-park","name":"ACAC Park 1","kind":"ground","country":"US","state":"Missouri","city":"Wentzville","address":"9620 Highway DD, Wentzville, MO 63385","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-veterans-field','ground','US','{"id":"us-veterans-field","name":"Veterans Cricket Field","kind":"ground","country":"US","state":"Virginia","city":"Woodbridge","address":"14300 Veterans Drive, Woodbridge, VA 22191","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-howe-athletic','ground','US','{"id":"us-howe-athletic","name":"Howe Athletic Cricket Ground","kind":"ground","country":"US","state":"New Jersey","city":"Somerset","address":"538 Elizabeth Avenue, Somerset, NJ","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-mercer-county','ground','US','{"id":"us-mercer-county","name":"Mercer County Park Cricket Ground","kind":"ground","country":"US","state":"New Jersey","city":"Princeton Junction","address":"334 South Post Road, Princeton Junction, NJ 08550","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-silver-star','ground','US','{"id":"us-silver-star","name":"Silver Star Recreation Center Cricket Ground","kind":"ground","country":"US","state":"Florida","city":"Orlando","address":"2801 N Apopka Vineland Road, Orlando, FL 32818","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-morgan-hill','ground','US','{"id":"us-morgan-hill","name":"Morgan Hill Outdoor Sports Center","kind":"ground","country":"US","state":"California","city":"Morgan Hill","address":"16500 Condit Road, Morgan Hill, CA 95037","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-woodley-park','ground','US','{"id":"us-woodley-park","name":"Woodley Park Cricket Complex","kind":"ground","country":"US","state":"California","city":"Van Nuys","address":"6350 Woodley Avenue, Van Nuys, CA 91406","latitude":null,"longitude":null,"level":"club","website":"https://www.laparks.org/sites/default/files/pdf/commissioner/2024/may16/24-100.pdf","sources":[{"url":"https://www.laparks.org/sites/default/files/pdf/commissioner/2024/may16/24-100.pdf","title":"Woodley Park Board Report | Los Angeles Recreation and Parks"}],"description":"Los Angeles park with cricket fields.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-canyonside','ground','US','{"id":"us-canyonside","name":"Canyonside Park Cricket Ground","kind":"ground","country":"US","state":"California","city":"San Diego","address":"12350 Black Mountain Road, San Diego, CA 92129","latitude":null,"longitude":null,"level":"club","website":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","sources":[{"url":"https://news.minorleaguecricket.com/2022/06/24/grounds-guide-attending-minor-league-matches/","title":"Grounds Guide | Minor League Cricket"},{"url":"https://www.sandiego.gov/sites/default/files/2026-05/prbr20260521a-item101.pdf","title":"Canyonside Community Park General Development Plan | City of San Diego"}],"description":"League cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-arroyo-park-davis','ground','US','{"id":"us-arroyo-park-davis","name":"Arroyo Park Cricket Ground","kind":"ground","country":"US","state":"California","city":"Davis","address":"2000 Shasta Drive, Davis, CA 95616","latitude":null,"longitude":null,"level":"club","website":"https://www.cityofdavis.org/Home/Components/FacilityDirectory/FacilityDirectory/280/2926","sources":[{"url":"https://www.cityofdavis.org/Home/Components/FacilityDirectory/FacilityDirectory/280/2926","title":"Arroyo Park - Cricket Field | City of Davis"}],"description":"City cricket field at Arroyo Park.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-tollgate-farms','ground','US','{"id":"us-tollgate-farms","name":"Tollgate Farms Park Cricket Ground","kind":"ground","country":"US","state":"Washington","city":"North Bend","address":"1300 W North Bend Way, North Bend, WA 98045","latitude":null,"longitude":null,"level":"club","website":"https://www.northbendwa.gov/Facilities/Facility/Details/36","sources":[{"url":"https://www.northbendwa.gov/Facilities/Facility/Details/36","title":"Tollgate Farm Park | City of North Bend"}],"description":"Public park with playfields used for cricket.","amenities":["restrooms","parking"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-atlanta-cricket-fields','ground','US','{"id":"us-atlanta-cricket-fields","name":"Atlanta Cricket Fields","kind":"ground","country":"US","state":"Georgia","city":"Cumming","address":"5325 Keith Bridge Road, Cumming, GA 30041","latitude":null,"longitude":null,"level":"club","website":"https://www.atlantacricketleague.org/Grounds","sources":[{"url":"https://www.atlantacricketleague.org/Grounds","title":"Grounds | Atlanta Cricket League"},{"url":"https://www.atlantacricketfields.com/","title":"Atlanta Cricket Fields"}],"description":"League-listed cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-bell-memorial','ground','US','{"id":"us-bell-memorial","name":"Bell Memorial Park Cricket Fields","kind":"ground","country":"US","state":"Georgia","city":"Milton","address":"15245 Bell Park Road, Milton, GA 30004","latitude":null,"longitude":null,"level":"grassroots","website":"https://www.atlantacricketleague.org/Grounds","sources":[{"url":"https://www.atlantacricketleague.org/Grounds","title":"Grounds | Atlanta Cricket League"}],"description":"League-listed cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-bennett-park','ground','US','{"id":"us-bennett-park","name":"Bennett Park Cricket Fields","kind":"ground","country":"US","state":"Georgia","city":"Cumming","address":"5930 Burruss Mill Road, Cumming, GA 30041","latitude":null,"longitude":null,"level":"grassroots","website":"https://www.atlantacricketleague.org/Grounds","sources":[{"url":"https://www.atlantacricketleague.org/Grounds","title":"Grounds | Atlanta Cricket League"}],"description":"League-listed cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-best-friend','ground','US','{"id":"us-best-friend","name":"Best Friend Park Cricket Field","kind":"ground","country":"US","state":"Georgia","city":"Norcross","address":"6224 Jimmy Carter Boulevard, Norcross, GA 30071","latitude":null,"longitude":null,"level":"grassroots","website":"https://www.atlantacricketleague.org/Grounds","sources":[{"url":"https://www.atlantacricketleague.org/Grounds","title":"Grounds | Atlanta Cricket League"}],"description":"League-listed cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-cauley-creek','ground','US','{"id":"us-cauley-creek","name":"Cauley Creek Park Cricket Field","kind":"ground","country":"US","state":"Georgia","city":"Johns Creek","address":"7255 Bell Road, Johns Creek, GA 30097","latitude":null,"longitude":null,"level":"grassroots","website":"https://www.atlantacricketleague.org/Grounds","sources":[{"url":"https://www.atlantacricketleague.org/Grounds","title":"Grounds | Atlanta Cricket League"}],"description":"League-listed cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('us-central-park-cumming','ground','US','{"id":"us-central-park-cumming","name":"Central Park Cricket Fields","kind":"ground","country":"US","state":"Georgia","city":"Cumming","address":"2300 Keith Bridge Road, Cumming, GA 30040","latitude":null,"longitude":null,"level":"grassroots","website":"https://www.atlantacricketleague.org/Grounds","sources":[{"url":"https://www.atlantacricketleague.org/Grounds","title":"Grounds | Atlanta Cricket League"}],"description":"League-listed cricket venue.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-narendra-modi-stadium','ground','IN','{"id":"in-narendra-modi-stadium","name":"Narendra Modi Stadium","kind":"ground","country":"IN","state":"Gujarat","city":"Ahmedabad","address":"Stadium Road, Motera, Sabarmati, Ahmedabad 380005","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-m-chinnaswamy-stadium','ground','IN','{"id":"in-m-chinnaswamy-stadium","name":"M. Chinnaswamy Stadium","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":"Mahatma Gandhi Road, near Cubbon Road, Bengaluru 560001","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-m-a-chidambaram-stadium','ground','IN','{"id":"in-m-a-chidambaram-stadium","name":"M.A. Chidambaram Stadium","kind":"ground","country":"IN","state":"Tamil Nadu","city":"Chennai","address":"Victoria Hostel Road, Chepauk, Chennai 600005","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-arun-jaitley-stadium','ground','IN','{"id":"in-arun-jaitley-stadium","name":"Arun Jaitley Stadium","kind":"ground","country":"IN","state":"Delhi","city":"New Delhi","address":"Bahadur Shah Zafar Marg, New Delhi 110002","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-hpca-stadium','ground','IN','{"id":"in-hpca-stadium","name":"HPCA Stadium","kind":"ground","country":"IN","state":"Himachal Pradesh","city":"Dharamshala","address":"HPCA Cricket Stadium, Kangra District, Dharamshala 176215","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-eden-gardens','ground','IN','{"id":"in-eden-gardens","name":"Eden Gardens","kind":"ground","country":"IN","state":"West Bengal","city":"Kolkata","address":"Eden Garden Road, Kolkata 700021","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-bharat-ratna-shri-atal-bihari-vajpayee-ekana-cricket-stadium','ground','IN','{"id":"in-bharat-ratna-shri-atal-bihari-vajpayee-ekana-cricket-stadium","name":"Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium","kind":"ground","country":"IN","state":"Uttar Pradesh","city":"Lucknow","address":"Sector 7, Amar Shaheed Path, Gomti Nagar, Lucknow 226010","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-wankhede-stadium','ground','IN','{"id":"in-wankhede-stadium","name":"Wankhede Stadium","kind":"ground","country":"IN","state":"Maharashtra","city":"Mumbai","address":"D Road, Churchgate, Mumbai 400020","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-mca-international-stadium','ground','IN','{"id":"in-mca-international-stadium","name":"MCA International Stadium","kind":"ground","country":"IN","state":"Maharashtra","city":"Pune","address":"Gahunje, Maharashtra 412101","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-rajiv-gandhi-international-stadium','ground','IN','{"id":"in-rajiv-gandhi-international-stadium","name":"Rajiv Gandhi International Stadium","kind":"ground","country":"IN","state":"Telangana","city":"Hyderabad","address":"Rajiv Gandhi International Stadium Road, Uppal, Hyderabad 500039","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-greenfield-international-stadium','ground','IN','{"id":"in-greenfield-international-stadium","name":"Greenfield International Stadium","kind":"ground","country":"IN","state":"Kerala","city":"Thiruvananthapuram","address":"Karyavattom, Thiruvananthapuram 695581","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-barsapara-cricket-stadium','ground','IN','{"id":"in-barsapara-cricket-stadium","name":"Barsapara Cricket Stadium","kind":"ground","country":"IN","state":"Assam","city":"Guwahati","address":"ACA Stadium, Barsapara, Guwahati 781018","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-aca-vdca-stadium','ground','IN','{"id":"in-aca-vdca-stadium","name":"ACA VDCA Stadium","kind":"ground","country":"IN","state":"Andhra Pradesh","city":"Visakhapatnam","address":"Pothinamallayya Palem, Visakhapatnam 530041","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-barabati-stadium','ground','IN','{"id":"in-barabati-stadium","name":"Barabati Stadium","kind":"ground","country":"IN","state":"Odisha","city":"Cuttack","address":"Barabati Stadium, Cuttack 753005","latitude":null,"longitude":null,"level":"international","website":"https://www.bcci.tv/venues?map=1","sources":[{"url":"https://www.bcci.tv/venues?map=1","title":"BCCI official venue directory"}],"description":"BCCI-listed international cricket venue.","amenities":["Floodlights"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-azad-maidan','ground','IN','{"id":"in-azad-maidan","name":"Azad Maidan","kind":"ground","country":"IN","state":"Maharashtra","city":"Mumbai","address":null,"latitude":null,"longitude":null,"level":"grassroots","website":"https://www.mumbaicricket.com/churchgate-to-mumbai-central","sources":[{"url":"https://www.mumbaicricket.com/churchgate-to-mumbai-central","title":"Mumbai Cricket Association ground directory"}],"description":"Association-listed community cricket ground.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cross-maidan','ground','IN','{"id":"in-cross-maidan","name":"Cross Maidan","kind":"ground","country":"IN","state":"Maharashtra","city":"Mumbai","address":null,"latitude":null,"longitude":null,"level":"grassroots","website":"https://www.mumbaicricket.com/churchgate-to-mumbai-central","sources":[{"url":"https://www.mumbaicricket.com/churchgate-to-mumbai-central","title":"Mumbai Cricket Association ground directory"}],"description":"Association-listed community cricket ground.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-oval-maidan','ground','IN','{"id":"in-oval-maidan","name":"Oval Maidan","kind":"ground","country":"IN","state":"Maharashtra","city":"Mumbai","address":null,"latitude":null,"longitude":null,"level":"grassroots","website":"https://www.mumbaicricket.com/churchgate-to-mumbai-central","sources":[{"url":"https://www.mumbaicricket.com/churchgate-to-mumbai-central","title":"Mumbai Cricket Association ground directory"}],"description":"Association-listed community cricket ground.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-shivaji-park-maidan','ground','IN','{"id":"in-shivaji-park-maidan","name":"Shivaji Park Maidan","kind":"ground","country":"IN","state":"Maharashtra","city":"Mumbai","address":null,"latitude":null,"longitude":null,"level":"grassroots","website":"https://www.mumbaicricket.com/dadar-to-borivali","sources":[{"url":"https://www.mumbaicricket.com/dadar-to-borivali","title":"Mumbai Cricket Association ground directory"}],"description":"Association-listed community cricket ground.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-central-maidan','ground','IN','{"id":"in-central-maidan","name":"Central Maidan","kind":"ground","country":"IN","state":"Maharashtra","city":"Thane","address":null,"latitude":null,"longitude":null,"level":"grassroots","website":"https://www.mumbaicricket.com/dadar-to-thane","sources":[{"url":"https://www.mumbaicricket.com/dadar-to-thane","title":"Mumbai Cricket Association ground directory"}],"description":"Association-listed community cricket ground.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-iisc-gymkhana-cricket-ground','ground','IN','{"id":"in-iisc-gymkhana-cricket-ground","name":"IISc Gymkhana Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-south-western-railways-institute-cricket-ground','ground','IN','{"id":"in-south-western-railways-institute-cricket-ground","name":"South Western Railways Institute Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-nra-palace-ground-cricket-ground','ground','IN','{"id":"in-nra-palace-ground-cricket-ground","name":"NRA Palace Ground Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-hal-sports-club-cricket-ground','ground','IN','{"id":"in-hal-sports-club-cricket-ground","name":"HAL Sports Club Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-nal-sports-executive-committee-cricket-ground','ground','IN','{"id":"in-nal-sports-executive-committee-cricket-ground","name":"NAL Sports Executive Committee Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-central-college-cricket-pavilion-cricket-ground','ground','IN','{"id":"in-central-college-cricket-pavilion-cricket-ground","name":"Central College Cricket Pavilion Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-mico-sports-club-cricket-ground','ground','IN','{"id":"in-mico-sports-club-cricket-ground","name":"MICO Sports Club Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-reva-institute-of-technology-and-management-cricket-ground','ground','IN','{"id":"in-reva-institute-of-technology-and-management-cricket-ground","name":"Reva Institute of Technology and Management Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-hmt-limited-sports-club-cricket-ground','ground','IN','{"id":"in-hmt-limited-sports-club-cricket-ground","name":"HMT Limited Sports Club Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-rail-wheel-factory-sports-association-cricket-ground','ground','IN','{"id":"in-rail-wheel-factory-sports-association-cricket-ground","name":"Rail Wheel Factory Sports Association Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-st-joseph-s-indian-high-school-cricket-ground','ground','IN','{"id":"in-st-joseph-s-indian-high-school-cricket-ground","name":"St Joseph’s Indian High School Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-infosys-cricket-club-cricket-ground','ground','IN','{"id":"in-infosys-cricket-club-cricket-ground","name":"Infosys Cricket Club Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-jp-nagar-stadium-cricket-ground','ground','IN','{"id":"in-jp-nagar-stadium-cricket-ground","name":"JP Nagar Stadium Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-bel-sports-club-cricket-ground','ground','IN','{"id":"in-bel-sports-club-cricket-ground","name":"BEL Sports Club Cricket Ground","kind":"ground","country":"IN","state":"Karnataka","city":"Bengaluru","address":null,"latitude":null,"longitude":null,"level":"club","website":"https://www.cricketkarnataka.com/grounds.aspx","sources":[{"url":"https://www.cricketkarnataka.com/grounds.aspx","title":"KSCA Karnataka Grounds directory"}],"description":"Cricket ground listed by the state association; public access needs operator confirmation.","amenities":[],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-berhampur','academy','IN','{"id":"in-cricket-academy-of-pathans-berhampur","name":"Cricket Academy of Pathans Berhampur","kind":"academy","country":"IN","state":"Odisha","city":"Berhampur","address":"Sams Ground, Berhampur, Ganjam, Odisha 760006","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-bhubaneswar','academy','IN','{"id":"in-cricket-academy-of-pathans-bhubaneswar","name":"Cricket Academy of Pathans Bhubaneswar","kind":"academy","country":"IN","state":"Odisha","city":"Bhubaneswar","address":"Loyola School, Chandrasekharpur, Bhubaneswar 751013","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-jaipur','academy','IN','{"id":"in-cricket-academy-of-pathans-jaipur","name":"Cricket Academy of Pathans Jaipur","kind":"academy","country":"IN","state":"Rajasthan","city":"Jaipur","address":"Kokali, Ward 17, Mukandpura Road, Bhakrota, Jaipur 302026","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-malihabad','academy','IN','{"id":"in-cricket-academy-of-pathans-malihabad","name":"Cricket Academy of Pathans Malihabad","kind":"academy","country":"IN","state":"Uttar Pradesh","city":"Malihabad","address":"Siddhartha Global School, Saiyad Bada, Mohan Road, Malihabad, Lucknow 226102","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-pune','academy','IN','{"id":"in-cricket-academy-of-pathans-pune","name":"Cricket Academy of Pathans Pune","kind":"academy","country":"IN","state":"Maharashtra","city":"Pune","address":"Memanwadi Phata, Mirawadi, Daund, Maharashtra 412207","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-guntur','academy','IN','{"id":"in-cricket-academy-of-pathans-guntur","name":"Cricket Academy of Pathans Guntur","kind":"academy","country":"IN","state":"Andhra Pradesh","city":"Guntur","address":"Vijay Kumar Memorial Ground, opposite Kesavreddy School, NH5 Service Road, Namburu, Guntur 522508","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-lucknow-bkt','academy','IN','{"id":"in-cricket-academy-of-pathans-lucknow-bkt","name":"Cricket Academy of Pathans Lucknow BKT","kind":"academy","country":"IN","state":"Uttar Pradesh","city":"Lucknow","address":"Chandrika Devi Road, opposite Ambkeshwar Institute AGI, Bakshi Ka Talab 226201","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-jammu','academy','IN','{"id":"in-cricket-academy-of-pathans-jammu","name":"Cricket Academy of Pathans Jammu","kind":"academy","country":"IN","state":"Jammu and Kashmir","city":"Jammu","address":"KC International School, Akhnoor Road, Paloura, Jammu 180002","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-muzaffarpur','academy','IN','{"id":"in-cricket-academy-of-pathans-muzaffarpur","name":"Cricket Academy of Pathans Muzaffarpur","kind":"academy","country":"IN","state":"Bihar","city":"Muzaffarpur","address":"Tirhut College of Physical Education, Krishnandan Sahay Nagar, Jhapaha, Muzaffarpur 842314","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-karnal','academy','IN','{"id":"in-cricket-academy-of-pathans-karnal","name":"Cricket Academy of Pathans Karnal","kind":"academy","country":"IN","state":"Haryana","city":"Karnal","address":"SS International School, Newal Road, ITI Chowk, Karnal 132001","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-dibrugarh','academy','IN','{"id":"in-cricket-academy-of-pathans-dibrugarh","name":"Cricket Academy of Pathans Dibrugarh","kind":"academy","country":"IN","state":"Assam","city":"Dibrugarh","address":"Sansys Smart School, Tingrai Chariali, Tingrai Nepali Gaon, Dibrugarh 786602","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-godhra','academy','IN','{"id":"in-cricket-academy-of-pathans-godhra","name":"Cricket Academy of Pathans Godhra","kind":"academy","country":"IN","state":"Gujarat","city":"Godhra","address":"Vijay Sports Academy, Survey 701, Daruniya Bypass Road, Dev Talavadi Mandir Road, Godhra","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-panvel','academy','IN','{"id":"in-cricket-academy-of-pathans-panvel","name":"Cricket Academy of Pathans Panvel","kind":"academy","country":"IN","state":"Maharashtra","city":"Panvel","address":"Karnala Sports Academy, opposite Kalsekar College, New Panvel, Raigad","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-madhubani','academy','IN','{"id":"in-cricket-academy-of-pathans-madhubani","name":"Cricket Academy of Pathans Madhubani","kind":"academy","country":"IN","state":"Bihar","city":"Madhubani","address":"Indian Public School, Stadium Road, Madhubani 847212","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-ajmer','academy','IN','{"id":"in-cricket-academy-of-pathans-ajmer","name":"Cricket Academy of Pathans Ajmer","kind":"academy","country":"IN","state":"Rajasthan","city":"Ajmer","address":"Ajmer-Jaipur Highway, opposite Gegal Police Station, Gegal, Ajmer 305023","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-gopalganj','academy','IN','{"id":"in-cricket-academy-of-pathans-gopalganj","name":"Cricket Academy of Pathans Gopalganj","kind":"academy","country":"IN","state":"Bihar","city":"Gopalganj","address":"Semra East, Thawe-Gopalganj Road, Gopalganj 841440","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-cricket-academy-of-pathans-alwar','academy','IN','{"id":"in-cricket-academy-of-pathans-alwar","name":"Cricket Academy of Pathans Alwar","kind":"academy","country":"IN","state":"Rajasthan","city":"Alwar","address":"Chikani, Rajasthan 301028","latitude":null,"longitude":null,"level":"training","website":"https://cricketacademyofpathans.com/centres/","sources":[{"url":"https://cricketacademyofpathans.com/centres/","title":"Cricket Academy of Pathans official centre directory"}],"description":"Cricket coaching centre in the operator’s directory.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-thoraipakkam','academy','IN','{"id":"in-super-kings-academy-thoraipakkam","name":"Super Kings Academy Thoraipakkam","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Chennai","address":"361 Madha Koil Street, Vivekananda Nagar, Thoraipakkam, Chennai","latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/facility-pricing","sources":[{"url":"https://www.superkingsacademy.com/facility-pricing","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-guru-nanak','academy','IN','{"id":"in-super-kings-academy-guru-nanak","name":"Super Kings Academy Guru Nanak","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Chennai","address":null,"latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/studentenrollment","sources":[{"url":"https://www.superkingsacademy.com/studentenrollment","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-srmc','academy','IN','{"id":"in-super-kings-academy-srmc","name":"Super Kings Academy SRMC","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Chennai","address":null,"latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/studentenrollment","sources":[{"url":"https://www.superkingsacademy.com/studentenrollment","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-vanagaram','academy','IN','{"id":"in-super-kings-academy-vanagaram","name":"Super Kings Academy Vanagaram","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Chennai","address":null,"latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/studentenrollment","sources":[{"url":"https://www.superkingsacademy.com/studentenrollment","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-akshar-arbol','academy','IN','{"id":"in-super-kings-academy-akshar-arbol","name":"Super Kings Academy Akshar Arbol","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Chennai","address":null,"latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/studentenrollment","sources":[{"url":"https://www.superkingsacademy.com/studentenrollment","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-ottiyambakkam','academy','IN','{"id":"in-super-kings-academy-ottiyambakkam","name":"Super Kings Academy Ottiyambakkam","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Chennai","address":null,"latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/studentenrollment","sources":[{"url":"https://www.superkingsacademy.com/studentenrollment","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-arumbakkam','academy','IN','{"id":"in-super-kings-academy-arumbakkam","name":"Super Kings Academy Arumbakkam","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Chennai","address":null,"latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/studentenrollment","sources":[{"url":"https://www.superkingsacademy.com/studentenrollment","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-super-kings-academy-trichy-kamala-niketan','academy','IN','{"id":"in-super-kings-academy-trichy-kamala-niketan","name":"Super Kings Academy Trichy – Kamala Niketan","kind":"academy","country":"IN","state":"Tamil Nadu","city":"Tiruchirappalli","address":"Kamala Niketan Montessori School, Tiruchirappalli","latitude":null,"longitude":null,"level":"training","website":"https://www.superkingsacademy.com/news-details/3003/3","sources":[{"url":"https://www.superkingsacademy.com/news-details/3003/3","title":"Super Kings Academy official centre information"}],"description":"Operator-listed cricket training centre.","amenities":["Cricket coaching"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-sharad-pawar-indoor-cricket-academy','practice','IN','{"id":"in-sharad-pawar-indoor-cricket-academy","name":"Sharad Pawar Indoor Cricket Academy","kind":"practice","country":"IN","state":"Maharashtra","city":"Mumbai","address":"Bandra-Kurla Complex, Mumbai","latitude":null,"longitude":null,"level":"training","website":"https://www.mumbaicricket.com/sharad-pawar","sources":[{"url":"https://www.mumbaicricket.com/sharad-pawar","title":"Mumbai Cricket Association indoor academy"}],"description":"Indoor cricket training facility operated by the Mumbai association.","amenities":["Indoor cricket"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_venues(id,kind,country,data,created) VALUES('in-just-cricket-academy','academy','IN','{"id":"in-just-cricket-academy","name":"Just Cricket Academy","kind":"academy","country":"IN","state":"Karnataka","city":"Bengaluru","address":"No. 7/1, Itgalpura village, Rajanukunte, Bengaluru, Karnataka 560064","latitude":null,"longitude":null,"level":"training","website":"https://www.justcric.com/","sources":[{"url":"https://www.justcric.com/","title":"Just Cricket Academy official site"}],"description":"Cricket academy with outdoor training wickets and indoor practice nets.","amenities":["Indoor astro nets","Outdoor turf wickets","Matting wickets","Gym"],"verifiedAt":"2026-10-07","bookingStatus":"directory-only","ownershipStatus":"unclaimed"}','2026-10-07T17:15:00Z');
--> statement-breakpoint
UPDATE content_reviews SET status='pending',reason='Automatic screening required for legacy public media' WHERE kind='asset' AND id IN (SELECT id FROM assets WHERE purpose='media' AND mime LIKE 'image/%');
--> statement-breakpoint
UPDATE content_reviews SET status='rejected',reason='Automatic video screening is not connected' WHERE kind='asset' AND id IN (SELECT id FROM assets WHERE mime LIKE 'video/%');
