import { sqliteTable, text, integer, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const records=sqliteTable('records',{id:text('id').primaryKey(),type:text('type').notNull(),owner:text('owner').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull()});
export const actions=sqliteTable('actions',{id:text('id').primaryKey(),recordId:text('record_id').notNull(),owner:text('owner').notNull(),kind:text('kind').notNull(),data:text('data').notNull(),created:text('created').notNull()},t=>[uniqueIndex('action_unique').on(t.recordId,t.owner,t.kind)]);
export const bookings=sqliteTable('bookings',{id:text('id').primaryKey(),recordId:text('record_id').notNull(),owner:text('owner').notNull(),date:text('date').notNull(),hour:integer('hour').notNull(),data:text('data').notNull(),created:text('created').notNull()},t=>[uniqueIndex('booking_slot').on(t.recordId,t.date,t.hour)]);
export const chats=sqliteTable('chats',{id:text('id').primaryKey(),owner:text('owner').notNull(),role:text('role').notNull(),content:text('content').notNull(),created:text('created').notNull()});
export const accounts=sqliteTable('accounts',{owner:text('owner').primaryKey(),email:text('email').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()});

export const assets=sqliteTable('assets',{id:text('id').primaryKey(),owner:text('owner').notNull(),key:text('key').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),created:text('created').notNull()});
export const sellerProfiles=sqliteTable('seller_profiles',{owner:text('owner').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()});
export const commerceOrders=sqliteTable('commerce_orders',{id:text('id').primaryKey(),buyer:text('buyer').notNull(),seller:text('seller').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()});
export const riderProfiles=sqliteTable('rider_profiles',{owner:text('owner').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()});
export const deliveryJobs=sqliteTable('delivery_jobs',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),seller:text('seller').notNull(),buyer:text('buyer').notNull(),rider:text('rider'),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[uniqueIndex('delivery_order_unique').on(t.orderId)]);
export const paymentAccounts=sqliteTable('payment_accounts',{id:text('id').primaryKey(),owner:text('owner').notNull(),role:text('role').notNull(),provider:text('provider').notNull(),accountId:text('account_id').notNull(),created:text('created').notNull()},t=>[uniqueIndex('payment_account_owner_role').on(t.owner,t.role)]);
export const payments=sqliteTable('payments',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),provider:text('provider').notNull(),providerId:text('provider_id').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull()},t=>[uniqueIndex('payment_order_unique').on(t.orderId)]);
export const payoutLedger=sqliteTable('payout_ledger',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),owner:text('owner').notNull(),role:text('role').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull()},t=>[uniqueIndex('payout_order_role').on(t.orderId,t.role)]);
export const platformRules=sqliteTable('platform_rules',{id:text('id').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(1)});
