const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
export const CAREER_CATEGORIES=['Playing','Coaching','Umpiring','Scoring','Grounds & facilities','Operations','Media & technology','Medical & fitness','Commercial','Volunteering','Other cricket role'];
export const CAREER_LEVELS=['Grassroots','Club','Academy','Domestic','National','International'];
export function validateJob(b){const d={};for(const[k,max]of Object.entries({name:160,organization:160,location:160,bio:6000,compensation:160,requirements:3000})){if(typeof b[k]!=='string'||!b[k].trim()||b[k].length>max)fail('Enter '+k);d[k]=b[k].trim()}if(!CAREER_CATEGORIES.includes(b.category)||!CAREER_LEVELS.includes(b.level)||!['Full-time','Part-time','Contract','Volunteer','Trial','Internship'].includes(b.contract)||!['On-site','Hybrid','Remote'].includes(b.workMode))fail('Choose valid role details');if(!/^\d{4}-\d{2}-\d{2}$/.test(b.deadline)||!Number.isFinite(Date.parse(b.deadline+'T23:59:59Z'))||new Date(b.deadline+'T00:00:00Z').toISOString().slice(0,10)!==b.deadline||b.deadline<new Date().toISOString().slice(0,10))fail('Choose a future deadline');if(b.authorized!==true||b.cricketRelated!==true)fail('Confirm authorization and cricket relevance');return {...d,category:b.category,level:b.level,contract:b.contract,workMode:b.workMode,deadline:b.deadline,status:'open',verification:'Self-declared organization; not independently verified',careerPortal:true}}
export async function careers(request,env,path,user,body){if(path[0]!=='careers')return null;const DB=env.DB,method=request.method;await DB.prepare('CREATE TABLE IF NOT EXISTS career_applications(id TEXT PRIMARY KEY,job_id TEXT NOT NULL,applicant TEXT NOT NULL,data TEXT NOT NULL,created TEXT NOT NULL,UNIQUE(job_id,applicant))').run();
if(!path[1]&&method==='GET'){const rows=(await DB.prepare("SELECT id,owner,data,version,created FROM records WHERE type='recruitment' ORDER BY created DESC LIMIT 500").all()).results;return json(rows.map(r=>({...JSON.parse(r.data),id:r.id,owner:r.owner,version:r.version,created:r.created})))}
if(!path[1]&&method==='POST'){const d=validateJob(await body()),id=crypto.randomUUID();await DB.prepare("INSERT INTO records(id,type,owner,data,created) VALUES(?,'recruitment',?,?,?)").bind(id,user,JSON.stringify(d),new Date().toISOString()).run();return json({id},201)}
if(path[1]==='applications'&&method==='GET')return json((await DB.prepare('SELECT a.*,r.data AS job_data FROM career_applications a JOIN records r ON r.id=a.job_id WHERE a.applicant=? ORDER BY a.created DESC LIMIT 200').bind(user).all()).results.map(r=>({...JSON.parse(r.data),id:r.id,jobId:r.job_id,jobName:JSON.parse(r.job_data).name,created:r.created})));
if(path[1]==='application'&&path[2]&&method==='POST'){const r=await DB.prepare('SELECT a.*,r.owner AS poster FROM career_applications a JOIN records r ON r.id=a.job_id WHERE a.id=?').bind(path[2]).first();if(!r)fail('Application not found',404);const b=await body(),d=JSON.parse(r.data);if(b.status==='withdrawn'){if(r.applicant!==user)fail('Only the applicant can withdraw',403)}else{if(r.poster!==user)fail('Only the poster can review applicants',403);if(!['reviewing','shortlisted','declined','selected'].includes(b.status))fail('Invalid application status');if(d.status==='withdrawn')fail('Application withdrawn',409)}d.status=b.status;await DB.prepare('UPDATE career_applications SET data=? WHERE id=? AND data=?').bind(JSON.stringify(d),r.id,r.data).run();return json({ok:true})}
const job=await DB.prepare("SELECT * FROM records WHERE id=? AND type='recruitment'").bind(path[1]).first();if(!job)fail('Opening not found',404);const d=JSON.parse(job.data);
if(path[2]==='apply'&&method==='POST'){if(job.owner===user)fail('You cannot apply to your own opening');if(d.status==='closed'||(d.deadline||d.date||'9999')<new Date().toISOString().slice(0,10))fail('This opening has closed',409);const b=await body();if(typeof b.cover!=='string'||!b.cover.trim()||b.cover.length>4000||b.consent!==true)fail('Add your introduction and consent to share it with the poster');let profileUrl='';if(b.profileUrl){let u;try{u=new URL(b.profileUrl)}catch{fail('Invalid profile URL')}if(u.protocol!=='https:'||u.username||u.password||b.profileUrl.length>500)fail('Use a safe HTTPS profile URL');profileUrl=u.href}const a=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(user).first(),data={name:JSON.parse(a.data).name,cover:b.cover.trim(),profileUrl,status:'submitted'};try{await DB.prepare('INSERT INTO career_applications(id,job_id,applicant,data,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),job.id,user,JSON.stringify(data),new Date().toISOString()).run()}catch(e){if(/unique/i.test(e.message))fail('You already applied',409);throw e}return json({ok:true},201)}
if(path[2]==='applicants'&&method==='GET'){if(job.owner!==user)fail('Only the poster can view applications',403);return json((await DB.prepare('SELECT id,data,created FROM career_applications WHERE job_id=? ORDER BY created DESC LIMIT 300').bind(job.id).all()).results.map(r=>({...JSON.parse(r.data),id:r.id,created:r.created})))}
if(path[2]==='close'&&method==='POST'){if(job.owner!==user)fail('Only the poster can close this opening',403);d.status='closed';const result=await DB.prepare('UPDATE records SET data=?,version=version+1 WHERE id=? AND owner=? AND version=?').bind(JSON.stringify(d),job.id,user,job.version).run();if(!result.meta.changes)fail('Opening changed; refresh',409);return json({ok:true})}return json({error:'Career endpoint not found'},404)}
