import {callApi} from './team-huddle.js';
import {admin} from './payments.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const rows=async(DB,sql,...args)=>(await DB.prepare(sql).bind(...args).all()).results;
const parse=r=>({...r,d:JSON.parse(r.data)});
const read=async(DB,id)=>{const r=await DB.prepare('SELECT * FROM carpool_rides WHERE id=?').bind(id).first();if(!r)fail('Ride not found',404);return parse(r);};
function txt(v,label,max=300,optional=false){if(optional&&(v===undefined||v===''))return '';if(typeof v!=='string'||v.length>max||!optional&&!v.trim())fail('Enter '+label);return v.trim();}
export function privateText(v,label,max=1000,optional=false){const s=txt(v,label,max,optional);if(/\b[^\s@]+@[^\s@]+\.[^\s@]+\b/.test(s)||/(?:\+?\d[\s().-]*){8,}/.test(s))fail('Use the consent button to request contact details; do not post phone numbers or email addresses.');return s;}
const accepted=d=>d.requests.filter(q=>q.status==='accepted');
const party=(q,u)=>[q.driver,q.rider].includes(u),other=(q,u)=>q.driver===u?q.rider:q.driver;
const blocked=async(DB,a,b)=>!!await DB.prepare('SELECT owner FROM carpool_blocks WHERE (owner=? AND target=?) OR (owner=? AND target=?)').bind(a,b,b,a).first();
export function splitEstimate(totalMinor,requests){const seats=requests.reduce((n,q)=>n+q.seats,0),people=seats+1,base=Math.floor(totalMinor/people),remainder=totalMinor%people;return {totalMinor,people,perSeatMinor:base,maxPerSeatMinor:base+(remainder?1:0),driverMinor:base+(remainder?1:0),byRequest:Object.fromEntries(requests.map((q,i)=>{const prior=requests.slice(0,i).reduce((n,v)=>n+v.seats,0);return [q.id,base*q.seats+Math.max(0,Math.min(q.seats,remainder-1-prior))];})),remainder,platformFeeMinor:0,collection:'Agree and settle directly; 18 does not charge or collect carpool money.'};}
async function identity(DB,u,teamId=''){const a=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(u).first();const profile=a?JSON.parse(a.data):{};let name=String(profile.name||'Cricket member').slice(0,100);try{name=privateText(name,'name',100)}catch{name='Cricket member';}let team='';if(teamId){const r=await DB.prepare("SELECT owner,data FROM records WHERE id=? AND type='teams'").bind(teamId).first();if(!r)fail('Choose an existing team');const h=await DB.prepare('SELECT data FROM team_hubs WHERE team_id=?').bind(teamId).first();if(r.owner!==u&&!(h&&JSON.parse(h.data).members.some(m=>m.userId===u&&m.status==='active')))fail('Choose a team you belong to',403);try{team=privateText(JSON.parse(r.data).name,'team name',100)}catch{team='Cricket team';}}return {name,team};}
const notify=(DB,u,r,title,requestId=null,guard=null)=>DB.prepare('INSERT INTO team_notifications(id,owner,team_id,data,created) SELECT ?,?,?,?,?'+(guard?' WHERE EXISTS(SELECT 1 FROM carpool_rides WHERE id=? AND json_extract(data,\'$.revisionKey\')=?)':'')).bind(uuid(),u,'carpool:'+r.id,JSON.stringify({kind:'carpool',title,rideId:r.id,requestId}),now(),...(guard?[r.id,guard]:[]));
async function commit(DB,r,d,b,title,recipients=[],extra=[]){if(b.version!==r.version)fail('Ride changed. Refresh before saving.',409);const key=uuid();d.revisionKey=key;const guard='EXISTS(SELECT 1 FROM carpool_rides WHERE id=? AND json_extract(data,\'$.revisionKey\')=?)';const x=await DB.batch([DB.prepare('UPDATE carpool_rides SET data=?,version=version+1,updated=? WHERE id=? AND version=?').bind(JSON.stringify(d),now(),r.id,r.version),...[...new Set([r.owner,...recipients])].map(u=>notify(DB,u,r,title,b.requestId||null,key)),...extra.map(fn=>fn(guard,r.id,key))]);if(!x[0].meta.changes)fail('Ride changed. Refresh before saving.',409);return json({ok:true,version:r.version+1});}
const liveRide=r=>r.d.status==='open'&&Date.parse(r.d.departAt)>Date.now();
async function tripContext(DB,b){const kind=b.contextKind||'community',id=b.contextId||'';if(!['community','match','tournament','league','academy','ground','practice','event'].includes(kind))fail('Choose a valid trip purpose');if(!id)return {kind,id:'',name:''};if(typeof id!=='string'||id.length>100)fail('Invalid destination reference');const types={match:'matches',tournament:'tournaments',league:'leagues',academy:'academies',ground:'grounds',event:'pickup',community:'community'};let r=await DB.prepare('SELECT type,data FROM records WHERE id=?').bind(id).first();if(r&&r.type===types[kind])return {kind,id,name:JSON.parse(r.data).name};if(['ground','practice','academy'].includes(kind)){r=await DB.prepare('SELECT kind,data FROM directory_venues WHERE id=?').bind(id).first();if(r&&r.kind===kind)return {kind,id,name:JSON.parse(r.data).name};}fail('Choose a matching cricket destination');}
export function validateRide(b){if(b.adultConsent!==true||b.costConsent!==true)fail('Confirm adult participation and voluntary cost sharing');const x={mode:b.mode==='need'?'need':'offer',origin:privateText(b.origin,'starting area',160),destination:privateText(b.destination,'destination',200),via:privateText(b.via,'route areas',300,true),departAt:txt(b.departAt,'departure time',50),returnAt:txt(b.returnAt,'return time',50,true),timeZone:txt(b.timeZone,'time zone',80),seats:Number(b.seats),currency:b.currency,totalMinor:Number(b.totalMinor),notes:privateText(b.notes,'trip preferences',1000,true),privatePickup:privateText(b.privatePickup,'private pickup instructions',600,true),vehicle:privateText(b.vehicle,'vehicle description',120,true),status:'open',requests:[],adultConsent:true,costConsent:true};if(!Number.isInteger(x.seats)||x.seats<1||x.seats>8)fail('Seats must be 1–8');if(!['USD','INR'].includes(x.currency)||!Number.isSafeInteger(x.totalMinor)||x.totalMinor<0||x.totalMinor>100000)fail('Enter voluntary travel cost in USD or INR, up to 1,000 units');try{new Intl.DateTimeFormat('en',{timeZone:x.timeZone});}catch{fail('Choose a valid time zone');}for(const k of ['departAt','returnAt'])if(x[k]&&(!/T.*(?:Z|[+-]\d\d:\d\d)$/.test(x[k])||!Number.isFinite(Date.parse(x[k]))))fail('Use date/time with an offset');if(Date.parse(x.departAt)<Date.now()+60000||Date.parse(x.departAt)>Date.now()+180*86400000)fail('Departure must be between one minute and 180 days from now');if(x.returnAt&&Date.parse(x.returnAt)<=Date.parse(x.departAt))fail('Return must follow departure');x.departAt=new Date(x.departAt).toISOString();if(x.returnAt)x.returnAt=new Date(x.returnAt).toISOString();return x;}
function publicRide(r,user){const d=r.d,confirmed=accepted(d);return {id:r.id,version:r.version,mine:r.owner===user,mode:d.mode,identity:d.identity,origin:d.origin,destination:d.destination,via:d.via,departAt:d.departAt,returnAt:d.returnAt,timeZone:d.timeZone,seats:d.seats,availableSeats:d.mode==='need'?(confirmed.length?0:d.seats):d.seats-confirmed.reduce((n,q)=>n+q.seats,0),currency:d.currency,totalMinor:d.totalMinor,notes:d.notes,status:d.status,context:d.context,cost:splitEstimate(d.totalMinor,confirmed),platformFeeMinor:0};}
async function requestView(DB,env,r,q,user){if(!party(q,user))fail('Ride participants only',403);if(await blocked(DB,q.driver,q.rider))return {id:q.id,status:q.status,blocked:true,rideId:r.id};const result={id:q.id,rideId:r.id,status:q.status,seats:q.seats,driver:q.driverIdentity,rider:q.riderIdentity,driverId:q.driver,riderId:q.rider,initialMessage:q.initialMessage,version:r.version,callConsent:!!q.callConsent?.[user],mutualCalling:!!q.callConsent?.[q.driver]&&!!q.callConsent?.[q.rider]&&q.status==='accepted'&&r.d.status==='open',phoneRequests:q.phoneRequests||{},callingConfigured:!!env.TEAM_TURN_URL&&!!env.TEAM_TURN_SECRET,messages:await rows(DB,'SELECT id,sender,body,created FROM carpool_messages WHERE request_id=? ORDER BY created DESC LIMIT 100',q.id)};result.messages.reverse();if(q.status==='accepted'){result.privatePickup=r.d.privatePickup;result.vehicle=r.d.vehicle;result.proposedCostMinor=q.proposedCostMinor??r.d.totalMinor;for(const [requester,p] of Object.entries(q.phoneRequests||{}))if(requester===user&&p.status==='granted'){const a=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(p.target).first();const phone=a?JSON.parse(a.data).phone:null;if(phone)result.sharedPhone=phone;}const calls=await rows(DB,'SELECT id,data,version,updated FROM team_calls WHERE team_id=? AND updated>? ORDER BY created DESC LIMIT 10','carpool-call:'+q.id,new Date(Date.now()-90000).toISOString());result.calls=calls.map(c=>({id:c.id,version:c.version,...JSON.parse(c.data)})).filter(c=>c.participants.some(p=>p.userId===user&&['invited','joined'].includes(p.state)));}return result;}
async function detail(DB,env,r,user){if(r.owner!==user&&await blocked(DB,r.owner,user))fail('Ride unavailable',404);const out=publicRide(r,user);out.requests=[];if(r.owner===user){out.privatePickup=r.d.privatePickup;out.vehicle=r.d.vehicle;}for(const q of r.d.requests)if(party(q,user))out.requests.push(await requestView(DB,env,r,q,user));return out;}
async function findRequest(DB,id){const r=await DB.prepare('SELECT * FROM carpool_rides WHERE EXISTS(SELECT 1 FROM json_each(json_extract(data,\'$.requests\')) WHERE json_extract(value,\'$.id\')=?)').bind(id).first();if(!r)fail('Carpool request not found',404);const parsed=parse(r);return {r:parsed,q:parsed.d.requests.find(q=>q.id===id)};}
export async function carpool(request,env,path,user,body){if(path[0]!=='carpool')return null;const DB=env.DB,method=request.method;
 if(path[1]==='reports'&&method==='GET'){if(!admin(request,env))fail('Platform operations only',403);return json(await rows(DB,'SELECT * FROM carpool_reports ORDER BY created DESC LIMIT 100'));}
 if(path[1]==='mine'&&method==='GET'){const all=await rows(DB,'SELECT * FROM carpool_rides WHERE owner=? OR EXISTS(SELECT 1 FROM json_each(json_extract(data,\'$.requests\')) WHERE json_extract(value,\'$.driver\')=? OR json_extract(value,\'$.rider\')=?) ORDER BY created DESC LIMIT 100',user,user,user);const output=[];for(const r of all){try{output.push(await detail(DB,env,parse(r),user));}catch(e){if(e.status!==404)throw e;}}return json(output);}
 if(path[1]==='rides'&&!path[2]){
  if(method==='GET'){const params=new URL(request.url).searchParams,offset=Number(params.get('offset')||0);if(!Number.isSafeInteger(offset)||offset<0||offset>10000)fail('Invalid page');const output=[];const list=await rows(DB,'SELECT * FROM carpool_rides WHERE json_extract(data,\'$.status\')=\'open\' AND json_extract(data,\'$.departAt\')>? AND NOT EXISTS(SELECT 1 FROM carpool_blocks b WHERE (b.owner=? AND b.target=carpool_rides.owner) OR (b.owner=carpool_rides.owner AND b.target=?)) ORDER BY json_extract(data,\'$.departAt\') LIMIT 100 OFFSET ?',now(),user,user,offset);for(const row of list){const r=parse(row),d=r.d;const match=['origin','destination'].every(k=>!params.get(k)||d[k].toLowerCase().includes(params.get(k).toLowerCase()));if(!match||params.get('contextId')&&params.get('contextId')!==d.context.id||params.get('mode')&&params.get('mode')!==d.mode||params.get('date')&&d.departAt.slice(0,10)!==params.get('date'))continue;output.push(publicRide(r,user));}return json({rides:output,nextOffset:list.length===100?offset+100:null,platformFeeMinor:0,matching:'Manual area, destination and date filters; no road-routing or live-location matching.'});}
  if(method==='POST'){const b=await body(),d=validateRide(b);d.context=await tripContext(DB,b);d.identity=await identity(DB,user,b.teamId||'');const id=uuid(),stamp=now(),x=await DB.prepare('INSERT INTO carpool_rides(id,owner,data,created,updated) SELECT ?,?,?,?,? WHERE (SELECT COUNT(*) FROM carpool_rides WHERE owner=? AND json_extract(data,\'$.status\')=\'open\' AND json_extract(data,\'$.departAt\')>?)<10').bind(id,user,JSON.stringify(d),stamp,stamp,user,stamp).run();if(!x.meta.changes)fail('You can have up to 10 upcoming rides',429);return json({id,platformFeeMinor:0},201);}
 }
 if(path[1]==='rides'&&path[2]){const r=await read(DB,path[2]);if(r.owner!==user&&await blocked(DB,r.owner,user))fail('Ride unavailable',404);if(method==='GET')return json(await detail(DB,env,r,user));
  if(path[3]==='report'&&method==='POST'){const b=await body(),reason=txt(b.reason,'report details',2000);const x=await DB.prepare('INSERT INTO carpool_reports(id,owner,ride_id,data,created) SELECT ?,?,?,?,? WHERE (SELECT COUNT(*) FROM carpool_reports WHERE owner=? AND created>?)<5').bind(uuid(),user,r.id,JSON.stringify({reason}),now(),user,new Date(Date.now()-86400000).toISOString()).run();if(!x.meta.changes)fail('Report limit reached',429);return json({ok:true,private:true});}
  if(path[3]==='requests'&&method==='POST'){if(r.owner===user)fail('You cannot request your own ride');if(!liveRide(r))fail('Ride is no longer open',409);const b=await body();if(b.adultConsent!==true||b.costConsent!==true)fail('Confirm adult participation and voluntary shared costs');if(r.d.requests.some(q=>party(q,user)&&['pending','accepted'].includes(q.status)))fail('You already have an active request for this ride',409);if(r.d.requests.length>=100)fail('This ride has reached its request limit');const seats=r.d.mode==='need'?r.d.seats:Number(b.seats);if(!Number.isInteger(seats)||seats<1||seats>r.d.seats)fail('Choose valid seat count');if(r.d.mode==='offer'&&seats>publicRide(r,user).availableSeats||r.d.mode==='need'&&accepted(r.d).length)fail('No matching seats available',409);if(r.d.mode==='need'&&b.driverConsent!==true)fail('Confirm you can drive and provide the requested seats');const applicant=await identity(DB,user,b.teamId||'');const q={id:uuid(),driver:r.d.mode==='offer'?r.owner:user,rider:r.d.mode==='offer'?user:r.owner,driverIdentity:r.d.mode==='offer'?r.d.identity:applicant,riderIdentity:r.d.mode==='offer'?applicant:r.d.identity,status:'pending',seats,initialMessage:privateText(b.message,'request message',1000,true),callConsent:{},phoneRequests:{},created:now(),...(r.d.mode==='need'?{proposedCostMinor:Number(b.proposedCostMinor)}:{})};if(r.d.mode==='need'&&(!Number.isSafeInteger(q.proposedCostMinor)||q.proposedCostMinor<0||q.proposedCostMinor>r.d.totalMinor))fail('Driver-proposed total expense must be within the stated budget');const d=structuredClone(r.d);d.requests.push(q);const result=await commit(DB,r,d,b,'New carpool request from '+applicant.name,[user]);return json({...await result.json(),requestId:q.id},201);}
  if(method==='POST'&&!path[3]){if(r.owner!==user)fail('Only the trip organiser can manage this listing',403);const b=await body(),d=structuredClone(r.d);if(!['cancel','complete','update'].includes(b.action))fail('Choose a trip action');if(b.action==='update'){if(d.requests.some(q=>['pending','accepted'].includes(q.status)))fail('This ride has requests. Cancel and publish a new ride for changed times, route or costs, so nobody travels on outdated terms.',409);const next=validateRide(b);next.context=await tripContext(DB,b);next.identity=d.identity;Object.assign(d,next);}else{d.status=b.action==='cancel'?'cancelled':'completed';for(const q of d.requests){q.callConsent={};q.phoneRequests={};if(b.action==='cancel'&&['pending','accepted'].includes(q.status))q.status='cancelled';}}return commit(DB,r,d,b,'Carpool trip '+b.action+'d',r.d.requests.flatMap(q=>[q.driver,q.rider]));}
 }
 if(path[1]==='requests'&&path[2]){const {r,q}=await findRequest(DB,path[2]);if(!party(q,user))fail('Ride request participants only',403);const isBlocked=await blocked(DB,q.driver,q.rider);
  if(path[3]==='calls'){if(isBlocked||q.status!=='accepted'||r.d.status!=='open'||!q.callConsent?.[q.driver]||!q.callConsent?.[q.rider])fail('Both accepted participants must consent to calls',403);const h={team:{id:'carpool-call:'+q.id},d:{members:[{userId:q.driver,name:q.driverIdentity.name,status:'active'},{userId:q.rider,name:q.riderIdentity.name,status:'active'}]}};if(method==='POST'&&path.length===4){const raw=await body();if(!Array.isArray(raw.recipients)||raw.recipients.length!==1||raw.recipients[0]!==other(q,user))fail('Call only your agreed carpool partner',403);return callApi(DB,env,h,user,['huddle',h.team.id,'calls'],method,async()=>raw,request);}return callApi(DB,env,h,user,['huddle',h.team.id,'calls',...path.slice(4)],method,body,request);}
  if(method==='GET')return json(await requestView(DB,env,r,q,user));
  if(path[3]==='messages'&&method==='POST'){if(isBlocked||!['pending','accepted'].includes(q.status)||r.d.status!=='open')fail('This conversation is closed',403);const b=await body(),message=privateText(b.body,'message',2000),id=uuid(),stamp=now();const x=await DB.batch([DB.prepare('INSERT INTO carpool_messages(id,ride_id,request_id,sender,body,created) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM carpool_rides WHERE id=? AND version=?) AND (SELECT COUNT(*) FROM carpool_messages WHERE sender=? AND created>?)<30').bind(id,r.id,q.id,user,message,stamp,r.id,r.version,user,new Date(Date.now()-60000).toISOString()),DB.prepare('INSERT INTO team_notifications(id,owner,team_id,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM carpool_messages WHERE id=?)').bind(uuid(),other(q,user),'carpool:'+r.id,JSON.stringify({kind:'carpool',title:'New carpool request message',rideId:r.id,requestId:q.id}),stamp,id)]);if(!x[0].meta.changes)fail('Ride changed or message limit reached. Refresh.',409);return json({id},201);}
  if(method==='POST'&&!path[3]){const b=await body(),d=structuredClone(r.d),x=d.requests.find(v=>v.id===q.id),all=r.d.requests.filter(q=>['pending','accepted'].includes(q.status)).flatMap(q=>[q.driver,q.rider]);if(isBlocked&&b.action!=='withdraw')fail('This interaction is blocked',403);
   if(['accept','decline'].includes(b.action)){if(r.owner!==user||x.status!=='pending'||!liveRide(r))fail('Only the organiser can decide a pending request before departure',403);if(b.action==='accept'){if(b.costConsent!==true)fail('Acknowledge the shared-cost estimate');if(d.mode==='offer'&&accepted(d).reduce((n,q)=>n+q.seats,0)+x.seats>d.seats||d.mode==='need'&&accepted(d).length)fail('Seats are already taken. Refresh.',409);x.status='accepted';x.agreedAt=now();if(d.mode==='need'){d.totalMinor=x.proposedCostMinor;for(const sibling of d.requests)if(sibling.id!==x.id&&sibling.status==='pending')sibling.status='declined';}}else x.status='declined';}
   else if(b.action==='withdraw'){if(!['pending','accepted'].includes(x.status))fail('Request is already closed',409);x.status='withdrawn';x.callConsent={};x.phoneRequests={};}
   else if(b.action==='no_show'){if(user!==x.driver||x.status!=='accepted'||Date.parse(d.departAt)>Date.now())fail('Only the driver can mark an accepted rider as a no-show after departure',403);x.status='no_show';x.callConsent={};x.phoneRequests={};}
   else if(b.action==='call-consent'){if(x.status!=='accepted'||d.status!=='open'||typeof b.consent!=='boolean')fail('Accepted trip and explicit call agreement required');x.callConsent[user]=b.consent;}
   else if(b.action==='phone-request'){if(x.status!=='accepted'||d.status!=='open')fail('Accept a ride before requesting a phone number',403);const old=x.phoneRequests[user];if(old?.status==='pending'||old?.status==='granted')fail('A phone request is already pending or granted',409);x.phoneRequests[user]={target:other(x,user),status:'pending',created:now()};}
   else if(b.action==='phone-decision'){if(x.status!=='accepted'||d.status!=='open')fail('Contact sharing is closed',403);const request=x.phoneRequests[other(x,user)];if(!request||request.target!==user||!['grant','decline','revoke'].includes(b.decision))fail('Choose a phone-sharing decision');if(b.decision==='grant'){const a=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(user).first();if(!a||!JSON.parse(a.data).phone)fail('Add a phone number to your private profile first');}request.status={grant:'granted',decline:'declined',revoke:'revoked'}[b.decision];}
   else if(b.action==='block'){x.status='withdrawn';x.callConsent={};x.phoneRequests={};return commit(DB,r,d,b,'Carpool interaction closed',[other(q,user)],[(guard,id,key)=>DB.prepare('INSERT OR IGNORE INTO carpool_blocks(owner,target,created) SELECT ?,?,? WHERE '+guard).bind(user,other(q,user),now(),id,key)]);}
   else fail('Unknown carpool request action');const attendees=['accept','decline','withdraw','no_show'].includes(b.action)?all:[q.driver,q.rider];return commit(DB,r,d,b,'Carpool request: '+b.action.replaceAll('-',' '),attendees);
  }
 }
 return json({error:'Carpool endpoint not found'},404);
}
