import {competitionAdmin} from './governance.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}),rows=async(DB,sql,...args)=>(await DB.prepare(sql).bind(...args).all()).results;
const text=(v,label,max=300)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail('Enter '+label);return v.trim();};
const member=(d,u)=>d.members.find(m=>m.owner===u&&m.status==='active');
const read=async(DB,id)=>{const r=await DB.prepare('SELECT * FROM expense_groups WHERE id=?').bind(id).first();if(!r)fail('Expense group not found',404);return {...r,d:JSON.parse(r.data)};};
export function splitExpense(amountMinor,selected,mode='equal'){if(!Number.isSafeInteger(amountMinor)||amountMinor<1||amountMinor>10000000||!Array.isArray(selected)||!selected.length||selected.length>100||new Set(selected.map(x=>x.key)).size!==selected.length)fail('Choose valid expense amount and unique participants');let weights;if(mode==='equal')weights=selected.map(()=>1);else if(mode==='exact'){if(selected.some(x=>!Number.isSafeInteger(x.amountMinor)||x.amountMinor<0)||selected.reduce((n,x)=>n+x.amountMinor,0)!==amountMinor)fail('Exact shares must add up to the expense total');return selected.map(x=>({key:x.key,amountMinor:x.amountMinor}));}else if(mode==='percentage'){if(selected.some(x=>!Number.isInteger(x.bps)||x.bps<0)||selected.reduce((n,x)=>n+x.bps,0)!==10000)fail('Percentage shares must add up to 100%');weights=selected.map(x=>x.bps);}else fail('Choose equal, exact or percentage splitting');const sum=weights.reduce((a,b)=>a+b,0),values=weights.map(w=>Math.floor(amountMinor*w/sum));let remainder=amountMinor-values.reduce((a,b)=>a+b,0);for(let i=0;remainder>0;i=(i+1)%values.length){if(weights[i]>0){values[i]++;remainder--;}}return selected.map((x,i)=>({key:x.key,amountMinor:values[i]}));}
export function suggestedSettlements(balances){const owing=Object.entries(balances).filter(([,n])=>n<0).map(([key,n])=>({key,amount:-n})),credit=Object.entries(balances).filter(([,n])=>n>0).map(([key,n])=>({key,amount:n})),result=[];let i=0,j=0;while(i<owing.length&&j<credit.length){const n=Math.min(owing[i].amount,credit[j].amount);result.push({from:owing[i].key,to:credit[j].key,amountMinor:n});owing[i].amount-=n;credit[j].amount-=n;if(!owing[i].amount)i++;if(!credit[j].amount)j++;}return result;}
function notice(DB,u,r,title,key){return DB.prepare('INSERT INTO team_notifications(id,owner,team_id,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM expense_groups WHERE id=? AND json_extract(data,\'$.revisionKey\')=?)').bind(uuid(),u,'finance:'+r.id,JSON.stringify({kind:'expense',title,groupId:r.id}),now(),r.id,key);}
async function save(DB,r,d,b,title,extra=[]){if(b.version!==r.version)fail('Group changed. Refresh before saving.',409);const key=uuid();d.revisionKey=key;const guard='EXISTS(SELECT 1 FROM expense_groups WHERE id=? AND json_extract(data,\'$.revisionKey\')=?)';const x=await DB.batch([DB.prepare('UPDATE expense_groups SET data=?,version=version+1,updated=? WHERE id=? AND version=?').bind(JSON.stringify(d),now(),r.id,r.version),...[...new Set(d.members.filter(m=>['active','invited'].includes(m.status)).map(m=>m.owner))].map(u=>notice(DB,u,r,title,key)),...extra.map(fn=>fn(guard,r.id,key))]);if(!x[0].meta.changes)fail('Group changed. Refresh.',409);return json({ok:true,version:r.version+1});}
async function groupView(DB,r,user){const d=structuredClone(r.d),my=d.members.filter(m=>m.owner===user);if(!my.length)fail('Group members only',403);if(!my.some(m=>m.status==='active'))return {id:r.id,name:d.name,currency:d.currency,version:r.version,invitation:true,context:d.context};delete d.revisionKey;const balances=Object.fromEntries(d.members.map(m=>[m.key,0]));for(const e of d.expenses){e.payments={};if(e.void)continue;balances[e.paidBy]+=e.amountMinor;for(const s of e.shares){balances[s.key]-=s.amountMinor;const payee=d.members.find(m=>m.key===e.paidBy),payer=d.members.find(m=>m.key===s.key);if(payee.owner===payer.owner){e.payments[s.key]={status:'own_share',settledMinor:s.amountMinor};balances[s.key]+=s.amountMinor;balances[e.paidBy]-=s.amountMinor;continue;}let state=e.settlements[s.key]?.status==='confirmed'?{status:'counterparty_confirmed',settledMinor:s.amountMinor,method:e.settlements[s.key].method}:{status:e.settlements[s.key]?.status==='claimed'?'claim_pending':'unpaid',settledMinor:0};if(e.orders[s.key]){const order=await DB.prepare('SELECT data FROM commerce_orders WHERE id=?').bind(e.orders[s.key]).first();if(order){const data=JSON.parse(order.data);state={...state,orderId:e.orders[s.key],providerStatus:data.paymentStatus};if(data.paymentStatus==='paid')state={...state,status:'provider_verified',settledMinor:s.amountMinor};if(['refunded','refund_pending'].includes(data.paymentStatus))state={...state,status:data.paymentStatus,settledMinor:0};}}e.payments[s.key]=state;if(state.settledMinor){balances[s.key]+=state.settledMinor;balances[e.paidBy]-=state.settledMinor;}}}return {id:r.id,version:r.version,manager:r.owner===user,...d,balances,suggestions:suggestedSettlements(balances),refunds:'Online refunds require platform operations; released payouts require provider reversal before refund.'};}
export async function expenseGroups(request,env,path,user,body){if(path[0]!=='expenses')return null;const DB=env.DB,method=request.method;
 if(!path[1]){
  if(method==='GET'){const list=await rows(DB,'SELECT * FROM expense_groups WHERE owner=? OR EXISTS(SELECT 1 FROM json_each(json_extract(data,\'$.members\')) WHERE json_extract(value,\'$.owner\')=? AND json_extract(value,\'$.status\') IN (\'active\',\'invited\')) ORDER BY created DESC LIMIT 100',user,user);return json(list.map(r=>({id:r.id,name:JSON.parse(r.data).name,currency:JSON.parse(r.data).currency,version:r.version,manager:r.owner===user})));}
  if(method==='POST'){const b=await body();if(!['USD','INR'].includes(b.currency))fail('Choose USD or INR');let eligible=[];const context={type:b.contextType||'custom',id:b.contextId||''};if(context.type==='team'){const t=await DB.prepare("SELECT * FROM records WHERE id=? AND type='teams'").bind(context.id).first();const h=await DB.prepare('SELECT data FROM team_hubs WHERE team_id=?').bind(context.id).first();const members=h?JSON.parse(h.data).members.filter(m=>m.status==='active'):[];if(!t||t.owner!==user&&!members.some(m=>m.userId===user&&m.role==='captain'))fail('Team owner or captain required',403);eligible=[{key:user,owner:user,name:'Group organiser'},...members.filter(m=>m.userId!==user).map(m=>({key:m.userId,owner:m.userId,name:m.name}))];}else if(context.type==='competition'){if(!await competitionAdmin(DB,context.id,user))fail('League or tournament administrator required',403);if(!Array.isArray(b.teamIds)||!b.teamIds.length||b.teamIds.length>50)fail('Choose teams to invite');eligible=[{key:user,owner:user,name:'Competition organiser'}];for(const id of new Set(b.teamIds)){const t=await DB.prepare("SELECT * FROM records WHERE id=? AND type='teams'").bind(id).first();if(!t)fail('Choose actual teams');if(t.owner===user)continue;eligible.push({key:'team:'+t.id,owner:t.owner,name:JSON.parse(t.data).name,teamId:t.id});}}else if(context.type==='custom'){if(!Array.isArray(b.playerIds)||b.playerIds.length>50)fail('Choose group players');eligible=[{key:user,owner:user,name:'Group organiser'}];for(const id of new Set(b.playerIds)){const p=await DB.prepare("SELECT * FROM records WHERE id=? AND type='players'").bind(id).first();if(!p)fail('Choose registered player profiles');if(p.owner===user||eligible.some(m=>m.owner===p.owner))continue;eligible.push({key:p.owner,owner:p.owner,name:JSON.parse(p.data).name});}}else fail('Choose a group context');const a=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(user).first();eligible[0].name=a?JSON.parse(a.data).name:'Group organiser';const d={name:text(b.name,'group name',160),currency:b.currency,context,members:eligible.map(m=>({...m,status:m.owner===user?'active':'invited'})),expenses:[],policy:'Payment requests are obligations entered by members, not automatic charges. Offline confirmations are distinct from provider verification.'};const id=uuid(),stamp=now(),r={id};await DB.batch([DB.prepare('INSERT INTO expense_groups(id,owner,data,created,updated) VALUES(?,?,?,?,?)').bind(id,user,JSON.stringify(d),stamp,stamp),...eligible.filter(m=>m.owner!==user).map(m=>DB.prepare('INSERT INTO team_notifications(id,owner,team_id,data,created) VALUES(?,?,?,?,?)').bind(uuid(),m.owner,'finance:'+id,JSON.stringify({kind:'expense',title:'Shared expense group invitation: '+d.name,groupId:id}),stamp))]);return json({id},201);}
 }
 const r=await read(DB,path[1]),my=member(r.d,user);if(method==='GET')return json(await groupView(DB,r,user));const b=await body(),d=structuredClone(r.d);
 if(path[2]==='invitation'&&method==='POST'){const pending=d.members.filter(m=>m.owner===user&&m.status==='invited');if(!pending.length||!['accept','decline'].includes(b.action))fail('No pending group invitation',403);pending.forEach(m=>m.status=b.action==='accept'?'active':'declined');return save(DB,r,d,b,'Expense group invitation '+b.action+'ed');}
 if(!my)fail('Accepted expense-group membership required',403);
 if(path[2]==='entries'&&!path[3]&&method==='POST'){if(d.expenses.length>=200)fail('Maximum 200 expenses per group');if(!['expense','dues'].includes(b.kind)||b.kind==='dues'&&r.owner!==user)fail('Only the group organiser can request dues',403);const payer=d.members.find(m=>m.key===b.paidBy&&m.status==='active');if(!payer||payer.owner!==user)fail('Record your own expense or collection only',403);const shares=splitExpense(Number(b.amountMinor),b.shares,b.splitMode);if(shares.some(s=>!d.members.some(m=>m.key===s.key&&m.status==='active')))fail('Invite participants and wait for acceptance before allocating expenses');const e={id:uuid(),title:text(b.title,'expense title',200),kind:b.kind,paidBy:b.paidBy,amountMinor:Number(b.amountMinor),shares,notes:String(b.notes||'').slice(0,1000),dueDate:b.dueDate||'',settlements:{},orders:{},created:now(),actor:user};if(e.dueDate&&!/^\d{4}-\d{2}-\d{2}$/.test(e.dueDate))fail('Invalid due date');d.expenses.push(e);return save(DB,r,d,b,'New '+b.kind+' request: '+e.title);}
 if(path[2]==='entries'&&path[3]&&method==='POST'){const e=d.expenses.find(e=>e.id===path[3]);if(!e||e.void)fail('Expense not found',404);const payee=d.members.find(m=>m.key===e.paidBy),share=e.shares.find(s=>s.key===b.shareKey),payer=share?d.members.find(m=>m.key===share.key):null;const view=await groupView(DB,r,user),current=view.expenses.find(x=>x.id===e.id);
  if(b.action==='void'){if(e.actor!==user&&r.owner!==user)fail('Expense creator or organiser required',403);if(Object.keys(e.orders).length||Object.values(e.settlements).some(s=>['claimed','confirmed'].includes(s.status)))fail('Resolve collections or refunds before voiding an expense',409);e.void=true;return save(DB,r,d,b,'Expense voided: '+e.title);}
  if(!share||!payer||share.amountMinor===0||payer.owner===payee.owner)fail('Choose a payable share');const payment=current.payments[share.key];
  if(b.action==='checkout'){if(payer.owner!==user)fail('Pay your own allocated share',403);if(env.EXPENSE_PAYMENTS_ENABLED!=='true')fail('Group collection activation is pending. Configure approved collector accounts and payment providers first.',503);if(['provider_verified','counterparty_confirmed','refund_pending'].includes(payment.status)||e.settlements[share.key]?.status==='claimed')fail('This share is paid or under reconciliation',409);if(e.orders[share.key])return json({orderId:e.orders[share.key],existing:true});const id=uuid(),stamp=now(),country=d.currency==='INR'?'IN':'US';const od={orderKind:'group_expense',expenseGroupId:r.id,expenseId:e.id,shareKey:share.key,product:{id:e.id,name:e.title,currency:d.currency,price:share.amountMinor/100,condition:'Service',returnDays:0,returnPolicy:'Expense collections are reconciled by the payee. Refunds require platform operations and any required transfer reversal.'},quantity:1,address:{country},delivery:'Group contribution',deliveryFee:0,total:share.amountMinor/100,status:'accepted',paymentStatus:'not_collected',commission:{grossMinor:share.amountMinor,commissionMinor:0,sellerMerchandiseMinor:share.amountMinor},history:[{status:'accepted',at:stamp,note:'Participant-accepted group expense; allocated amount fixed on server'}]};e.orders[share.key]=id;const result=await save(DB,r,d,b,'Checkout prepared for '+e.title,[(guard,gid,key)=>DB.prepare('INSERT INTO commerce_orders(id,buyer,seller,data,created,updated) SELECT ?,?,?,?,?,? WHERE '+guard).bind(id,user,payee.owner,JSON.stringify(od),stamp,stamp,gid,key)]);return json({...await result.json(),orderId:id});}
  if(b.action==='claim'){if(payer.owner!==user)fail('Only the allocated payer can report a transfer',403);if(e.orders[share.key]||['provider_verified','counterparty_confirmed'].includes(payment.status)||e.settlements[share.key]?.status==='claimed')fail('Resolve the existing payment or claim first',409);const allowed=d.currency==='INR'?['UPI','Bank transfer','Cash']:['Zelle','Venmo','Cash App','Bank transfer','Cash','PayPal'];if(!allowed.includes(b.method))fail('Choose a supported direct-payment record');e.settlements[share.key]={status:'claimed',method:b.method,reference:text(b.reference,'payment reference / note',200),reportedBy:user,created:now()};return save(DB,r,d,b,'Direct payment reported, awaiting recipient confirmation');}
  if(b.action==='confirm'||b.action==='reject'){if(payee.owner!==user||e.settlements[share.key]?.status!=='claimed')fail('Only the recipient can reconcile a pending direct transfer',403);e.settlements[share.key].status=b.action==='confirm'?'confirmed':'rejected';e.settlements[share.key].reviewedAt=now();return save(DB,r,d,b,'Direct payment '+b.action+'ed; this is not provider verification');}
  if(b.action==='refund-request'){if(payee.owner!==user||payment.status!=='provider_verified'||!e.orders[share.key])fail('Only the recipient can request reconciliation of a verified online collection',403);const o=await DB.prepare('SELECT * FROM commerce_orders WHERE id=?').bind(e.orders[share.key]).first();const od=JSON.parse(o.data);od.return={status:'received',reason:'Group contribution refund requested by recipient',requestedAt:now()};return save(DB,r,d,b,'Contribution refund requested; operations approval required',[(guard,gid,key)=>DB.prepare('UPDATE commerce_orders SET data=?,version=version+1,updated=? WHERE id=? AND version=? AND '+guard).bind(JSON.stringify(od),now(),o.id,o.version,gid,key)]);}
  if(b.action==='remind'){if(payee.owner!==user||payment.settledMinor)fail('Only the recipient can remind an unpaid participant',403);const last=e.reminders?.[share.key];if(last&&Date.parse(last)>Date.now()-86400000)fail('One reminder per share per day',429);e.reminders??={};e.reminders[share.key]=now();return save(DB,r,d,b,'Payment reminder: '+e.title);}
  fail('Unknown expense action');
 }
 return json({error:'Expense endpoint not found'},404);
}
