import {appendCommand} from '../public/scoring-engine.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const now=()=>new Date().toISOString();
const record=async(DB,id)=>DB.prepare('SELECT * FROM records WHERE id=?').bind(id).first();
export async function competitionAdmin(DB,id,user){const r=await record(DB,id);if(!r||!['tournaments','leagues'].includes(r.type))return false;if(r.owner===user)return true;if(await DB.prepare('SELECT owner FROM competition_admins WHERE competition_id=? AND owner=?').bind(id,user).first())return true;const d=JSON.parse(r.data);if(r.type==='tournaments'&&d.leagueId){const league=await record(DB,d.leagueId);return league?.type==='leagues'&&(league.owner===user||!!await DB.prepare('SELECT owner FROM competition_admins WHERE competition_id=? AND owner=?').bind(league.id,user).first())}return false}
export async function canAdminMatch(DB,r,user){const d=JSON.parse(r.data);return d.tournamentId?competitionAdmin(DB,d.tournamentId,user):d.leagueId?competitionAdmin(DB,d.leagueId,user):r.owner===user}
export async function proposeChange(DB,r,user,change){if(r.owner!==user&&!await canAdminMatch(DB,r,user))fail('Only the assigned scorer or a competition admin can propose changes',403);if(change.version!==r.version)fail('Scorecard changed. Refresh.',409);const id=crypto.randomUUID();await DB.prepare('INSERT INTO match_changes(id,match_id,owner,data,created) VALUES(?,?,?,?,?)').bind(id,r.id,user,JSON.stringify({...change,before:JSON.parse(r.data)}),now()).run();return json({id,pendingApproval:true,message:'Change submitted to competition admins. The current scorecard is unchanged.'},202)}
export async function governance(request,env,path,user,body){if(path[0]!=='governance')return null;const DB=env.DB,method=request.method;
if(path[1]==='competitions'&&method==='GET'){const rows=(await DB.prepare("SELECT * FROM records WHERE type IN ('tournaments','leagues')").all()).results;const output=[];for(const r of rows)if(await competitionAdmin(DB,r.id,user))output.push({id:r.id,name:JSON.parse(r.data).name,type:r.type,creator:r.owner,isCreator:r.owner===user});return json(output)}
if(path[1]==='admins'){const r=await record(DB,path[2]);if(!r||!['tournaments','leagues'].includes(r.type))fail('Competition not found',404);if(!await competitionAdmin(DB,r.id,user))fail('Competition admin required',403);
 if(method==='GET'){const rows=(await DB.prepare('SELECT c.owner,a.email FROM competition_admins c LEFT JOIN accounts a ON a.owner=c.owner WHERE competition_id=?').bind(r.id).all()).results;return json({creator:r.owner,admins:rows})}
 if(method==='POST'||method==='DELETE'){if(r.owner!==user)fail('Only the competition creator can appoint or remove admins',403);const b=await body();const account=await DB.prepare('SELECT owner FROM accounts WHERE lower(email)=lower(?)').bind(String(b.email||'')).first();if(!account)fail('That person must register an account first');if(account.owner===r.owner)fail('The creator remains an admin');if(method==='POST')await DB.prepare('INSERT OR IGNORE INTO competition_admins(competition_id,owner,created) VALUES(?,?,?)').bind(r.id,account.owner,now()).run();else await DB.prepare('DELETE FROM competition_admins WHERE competition_id=? AND owner=?').bind(r.id,account.owner).run();return json({ok:true})}}
if(path[1]==='changes'&&method==='GET'){const rows=(await DB.prepare("SELECT * FROM match_changes ORDER BY created DESC LIMIT 1000").all()).results;const output=[];for(const change of rows){const r=await record(DB,change.match_id);if(r&&(change.owner===user||await canAdminMatch(DB,r,user)))output.push({...change,matchName:JSON.parse(r.data).name,data:JSON.parse(change.data),canReview:await canAdminMatch(DB,r,user)})}return json(output)}
if(path[1]==='changes'&&path[2]&&method==='POST'){const c=await DB.prepare('SELECT * FROM match_changes WHERE id=?').bind(path[2]).first();if(!c)fail('Change request not found',404);const r=await record(DB,c.match_id);if(!r||!await canAdminMatch(DB,r,user))fail('Competition admin approval required',403);if(c.status!=='pending')fail('This request has already been reviewed',409);const b=await body();if(!['approve','reject'].includes(b.decision))fail('Choose approve or reject');const change=JSON.parse(c.data);if(b.decision==='approve'&&r.version!==change.version)fail('Scorecard changed. Reject this request and submit a fresh correction.',409);
 let d=JSON.parse(r.data);if(b.decision==='approve'){if(change.kind==='details')d={...d,...change.data};else if(change.kind==='setup')d=change.data;else if(change.kind==='score'){if(d.proScoring){try{d=appendCommand(d,change.input)}catch(e){fail(e.message)}}else if(change.input.undo){if(d.firstClosed&&!(d.events||[]).some(e=>e.innings===2))d.firstClosed=false;else d.events=(d.events||[]).slice(0,-1)}else fail('Unsupported legacy correction')}else fail('Invalid change type')}
 const stamp=now(),status=b.decision==='approve'?'approved':'rejected';const queries=[DB.prepare("UPDATE match_changes SET status=?,reviewed_by=?,reviewed_at=? WHERE id=? AND status='pending' AND (?='rejected' OR EXISTS(SELECT 1 FROM records WHERE records.id=match_changes.match_id AND records.version=?))").bind(status,user,stamp,c.id,status,change.version)];if(b.decision==='approve')queries.push(DB.prepare('UPDATE records SET data=?,version=version+1 WHERE id=? AND version=? AND changes()=1').bind(JSON.stringify(d),r.id,r.version));const results=await DB.batch(queries);if(!results[0].meta.changes||b.decision==='approve'&&!results[1].meta.changes)fail('Review conflict. Refresh.',409);return json({ok:true,status});}
return json({error:'Governance endpoint not found'},404)}
