import {admin,rules,saveOrder,sellerEarning} from './payments.js';
import {route,point} from './maps.js';
import {deliveryQuote,commissionQuote} from './economics.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},json=d=>new Response(JSON.stringify(d),{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}),now=()=>new Date().toISOString();
const hash=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');
export async function rushQuote(env,DB,seller,address){const pickup=point(seller.pickupPoint),drop=point(address.point);const road=await route(env,pickup,drop);return {...deliveryQuote(address.country,road.distanceMeters,road.durationSeconds,await rules(DB)),pickup,drop,pickupAddress:seller.pickupAddress||seller.returnAddress,pickupPhone:seller.contactPhone,source:road.source}}
const profile=async(DB,user)=>{const r=await DB.prepare('SELECT * FROM rider_profiles WHERE owner=?').bind(user).first();return r?{...JSON.parse(r.data),version:r.version}:null};
async function updateJob(DB,r,d,rider=r.rider){const x=await DB.prepare('UPDATE delivery_jobs SET data=?,rider=?,version=version+1,updated=? WHERE id=? AND version=?').bind(JSON.stringify(d),rider,now(),r.id,r.version).run();if(!x.meta.changes)fail('Delivery changed. Refresh.',409)}
export async function riders(request,env,path,user,body){if(path[0]!=='riders')return null;const DB=env.DB,method=request.method;
if(path[1]==='profile'){if(method==='GET')return json({profile:await profile(DB,user)});if(method==='POST'){const b=await body(),d=b.data||{},old=await profile(DB,user);if(old&&b.version!==old.version)fail('Rider profile changed. Reload.',409);if(!['US','IN'].includes(d.country)||!['Car','Motorcycle','Bicycle','Van'].includes(d.vehicle)||!d.name?.trim()||!d.phone?.trim()||d.agreement!==true||d.ageConfirmed!==true)fail('Complete your profile, confirm you are 18+, and accept delivery terms');const postalCodes=String(d.postalCodes||'').split(',').map(x=>x.trim()).filter(Boolean);if(!postalCodes.length||postalCodes.length>100||postalCodes.some(x=>!(d.country==='US'?/^\d{5}$/:/^\d{6}$/).test(x)))fail('Enter valid serviceable PIN/ZIP codes');const data={name:String(d.name).slice(0,120),phone:String(d.phone).slice(0,40),country:d.country,city:String(d.city||'').slice(0,120),vehicle:d.vehicle,postalCodes,status:old?.status==='approved'?'approved':'pending',available:old?.status==='approved'&&d.available===true,foodHandlingAccepted:d.foodHandlingAccepted===true,insulatedBagConfirmed:d.insulatedBagConfirmed===true,agreement:true,ageConfirmed:true,notes:String(d.notes||'').slice(0,500)};if(old?.country!==data.country||old?.vehicle!==data.vehicle)data.status='pending';if(data.status!=='approved')data.available=false;const stamp=now();if(old){const r=await DB.prepare('UPDATE rider_profiles SET data=?,version=version+1,updated=? WHERE owner=? AND version=?').bind(JSON.stringify(data),stamp,user,old.version).run();if(!r.meta.changes)fail('Rider profile changed',409)}else await DB.prepare('INSERT INTO rider_profiles(owner,data,created,updated) VALUES(?,?,?,?)').bind(user,JSON.stringify(data),stamp,stamp).run();return json({ok:true})}}
if(path[1]==='approve'&&method==='POST'){if(!admin(request,env))fail('Platform administrator required',403);const b=await body(),p=await profile(DB,b.owner);if(!p||p.version!==b.version)fail('Rider application changed',409);if(!['approved','rejected','suspended'].includes(b.status)||!b.note?.trim())fail('Record review outcome and verification note');const d={...p,status:b.status,available:false,reviewNote:String(b.note).slice(0,500),reviewedAt:now()};delete d.version;await DB.prepare('UPDATE rider_profiles SET data=?,version=version+1,updated=? WHERE owner=? AND version=?').bind(JSON.stringify(d),now(),b.owner,p.version).run();return json({ok:true})}
if(path[1]==='quote'&&method==='POST'){const b=await body(),s=await DB.prepare('SELECT data FROM seller_profiles WHERE owner=?').bind(b.sellerId).first();if(!s)fail('Seller not found');const seller=JSON.parse(s.data);if(!seller.pitchRush||!seller.postalCodes.includes(String(b.address?.postal))||b.address?.country!==seller.country)fail('Seller does not serve this area');const quote=await rushQuote(env,DB,seller,{...b.address,point:point(b.address?.point)});return json({riderMinor:quote.riderMinor,buyerMinor:quote.buyerMinor,platformMinor:quote.platformMinor,currency:quote.currency,distance:quote.distance,unit:quote.unit,durationSeconds:quote.durationSeconds,basis:quote.basis})}
if(path[1]==='jobs'){
if(method==='GET'){const rows=(await DB.prepare('SELECT * FROM delivery_jobs ORDER BY created DESC LIMIT 500').all()).results,p=await profile(DB,user);const list=[];for(const r of rows){const d=JSON.parse(r.data),participant=[r.rider,r.buyer,r.seller].includes(user);if(participant){const copy={...d};delete copy.handoverHash;if(r.buyer!==user)delete copy.handoverCode;list.push({...copy,id:r.id,orderId:r.order_id,rider:r.rider,buyer:r.buyer,seller:r.seller,version:r.version})}else if(p?.status==='approved'&&p.available&&d.status==='offered'&&d.country===p.country&&p.postalCodes.includes(d.pickupPostal)&&(d.orderKind!=='food'||p.foodHandlingAccepted&&p.insulatedBagConfirmed)){list.push({id:r.id,version:r.version,status:d.status,country:d.country,pickupCity:d.pickupCity,dropCity:d.dropCity,pickupPostal:d.pickupPostal,quote:d.quote,productName:d.productName,orderKind:d.orderKind||'equipment'})}}return json(list)}
if(method==='POST'&&path[2]){const b=await body();if(b.action==='publish'){const r=await DB.prepare('SELECT * FROM commerce_orders WHERE id=?').bind(path[2]).first();if(!r||r.seller!==user)fail('Only seller can offer delivery',403);const d=JSON.parse(r.data);if(d.delivery!=='PitchRush'||d.paymentStatus!=='paid'||!d.riderQuote||!['accepted','packing'].includes(d.status))fail('A paid PitchRush order with a road-distance quote is required');if(d.orderKind==='food'&&d.foodStage!=='ready')fail('Meals must be ready before offering delivery',409);const seller=await DB.prepare(d.orderKind==='food'?'SELECT data FROM restaurant_profiles WHERE owner=?':'SELECT data FROM seller_profiles WHERE owner=?').bind(user).first();if(!seller)fail('Pickup profile unavailable');const s=JSON.parse(seller.data),q=d.riderQuote,code=String(crypto.getRandomValues(new Uint32Array(1))[0]%900000+100000);const value={orderKind:d.orderKind||'equipment',status:'offered',country:d.address.country,pickupCity:s.city,pickupPostal:s.postal,dropCity:d.address.city,productName:d.product.name,quote:{baseRiderMinor:q.riderMinor,tipMinor:d.orderKind==='food'?(d.tipMinor||0):0,riderMinor:q.riderMinor+(d.orderKind==='food'?(d.tipMinor||0):0),buyerMinor:q.buyerMinor+(d.orderKind==='food'?(d.tipMinor||0):0),currency:q.currency,distance:q.distance,unit:q.unit,durationSeconds:q.durationSeconds,basis:q.basis},pickup:q.pickup,drop:q.drop,pickupAddress:q.pickupAddress,pickupPhone:q.pickupPhone,dropAddress:d.address,handoverCode:code,handoverHash:await hash(code),history:[{status:'offered',at:now()}]};try{await DB.prepare('INSERT INTO delivery_jobs(id,order_id,seller,buyer,data,created,updated) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),r.id,r.seller,r.buyer,JSON.stringify(value),now(),now()).run()}catch(e){if(/unique/i.test(e.message))fail('A delivery already exists for this order',409);throw e}return json({ok:true})}
const r=await DB.prepare('SELECT * FROM delivery_jobs WHERE id=?').bind(path[2]).first();if(!r)fail('Delivery not found',404);if(b.version!==r.version)fail('Delivery changed. Refresh.',409);const d=JSON.parse(r.data),p=await profile(DB,user),action=b.action;let rider=r.rider;if(action==='claim'){if(p?.status!=='approved'||p.vehicle==='Bicycle'||!p.available||r.rider||d.status!=='offered'||d.country!==p.country||!p.postalCodes.includes(d.pickupPostal)||[r.buyer,r.seller].includes(user)||d.orderKind==='food'&&(!p.foodHandlingAccepted||!p.insulatedBagConfirmed))fail('This delivery is not available to you',403);d.status='assigned';rider=user}
else if(action==='picked_up'){if(r.rider!==user||p?.status!=='approved'||d.status!=='assigned')fail('Only assigned rider can record pickup',403);d.status='in_transit';d.pickedUpAt=now();const o=await DB.prepare('SELECT * FROM commerce_orders WHERE id=?').bind(r.order_id).first(),od=JSON.parse(o.data);if(od.paymentStatus!=='paid')fail('Payment is not available',409);od.status='out_for_delivery';od.shipping={carrier:'PitchRush rider',dispatchedAt:now()};await saveOrder(DB,o,od)}
else if(action==='complete'){if(r.rider!==user||p?.status!=='approved'||d.status!=='in_transit')fail('Only assigned rider can complete delivery',403);if(!['Handover','Drop-off photo'].includes(b.method))fail('Choose completion method');if(b.method==='Handover'){if(!b.code||await hash(String(b.code))!==d.handoverHash)fail('Ask the buyer for their handover code',403)}else{const asset=await DB.prepare('SELECT * FROM assets WHERE id=? AND owner=?').bind(b.photoId,user).first();if(!asset||!asset.mime.startsWith('image/'))fail('Upload your delivery photo');d.proofPhotoId=b.photoId}d.proofPoint=point(b.point,false);d.method=b.method;d.status=b.method==='Handover'?'completed':'proof_review';d.completedAt=now();d.proofNote=String(b.note||'').slice(0,500)}
else if(action==='finalize'){if(d.status!=='completed'||![r.rider,r.buyer,r.seller].includes(user))fail('Completed delivery participants only',403)}
else if(action==='approve_proof'){if(![r.buyer,r.seller].includes(user)||d.status!=='proof_review')fail('Buyer or seller must review the drop-off photo',403);d.status='completed';d.proofApprovedAt=now()}
else fail('Invalid delivery action');d.history.push({status:d.status,at:now()});await updateJob(DB,r,d,rider);if(d.status==='completed'){const o=await DB.prepare('SELECT * FROM commerce_orders WHERE id=?').bind(r.order_id).first(),od=JSON.parse(o.data);if(od.paymentStatus!=='paid')fail('Payment must be verified',409);if(od.status!=='delivered'){od.status='delivered';if(od.orderKind==='food')od.foodStage='completed';od.deliveredAt=d.completedAt;await saveOrder(DB,o,od);}const ld={amountMinor:d.quote.riderMinor,tipMinor:d.quote.tipMinor||0,baseDeliveryMinor:d.quote.baseRiderMinor??d.quote.riderMinor,currency:d.quote.currency,status:'held',releaseAt:new Date(Date.now()+86400000).toISOString(),basis:d.quote.basis};await DB.prepare('INSERT OR IGNORE INTO payout_ledger(id,order_id,owner,role,data,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),r.order_id,rider,'rider',JSON.stringify(ld),now()).run();await sellerEarning(DB,{...o,data:JSON.stringify(od)})}return json({ok:true})}
}
return json({error:'Rider endpoint not found'})}
