import {validateMatchSetup} from './match-setup.js';
import {calculateMatch,appendCommand,playerPerformance} from '../public/scoring-engine.js';
import {proposeChange} from './governance.js';
import {canAdminMatch} from './governance.js';
import {drsReadiness} from './drs.js';
import {contentReviewStatement,contentApproved,moderateImage,checkText} from './content-safety.js';
import {admin} from './payments.js';
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...h}});
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})};
const now=()=>new Date().toISOString();
const read=async(DB,id)=>{const r=await DB.prepare('SELECT * FROM records WHERE id=?').bind(id).first();if(!r)fail('Record not found',404);return r};
const own=(r,u)=>{if(r.owner!==u)fail('Only the owner can change this record',403)};
const save=async(DB,r,d)=>{const a=await DB.prepare('UPDATE records SET data=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(d),r.id,r.version).run();if(!a.meta.changes)fail('Record changed. Refresh and try again.',409)};
export function streamEmbed(url){try{const u=new URL(url);if(u.protocol!=='https:')return null;let video;if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname)){video=u.searchParams.get('v')||u.pathname.match(/^\/(?:live|embed|shorts)\/([\w-]{11})/)?.[1]}else if(u.hostname==='youtu.be')video=u.pathname.slice(1);if(video&&/^[\w-]{11}$/.test(video))return 'https://www.youtube-nocookie.com/embed/'+video;if(['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(u.hostname)){const n=u.pathname.match(/(?:video\/)?(\d+)$/)?.[1];if(n)return 'https://player.vimeo.com/video/'+n}return null}catch{return null}}
export async function validateSocial(DB,user,data,existing){if(!data||typeof data!=='object'||Array.isArray(data))fail('Invalid post');const d={};for(const k of ['name','bio','url','image','mediaId','postType','sourceMatchId','status'])if(data[k]!==undefined){if(typeof data[k]!=='string'||data[k].length>(k==='bio'?4000:500))fail('Invalid social field');d[k]=data[k].trim()}if(!d.name)fail('Add a title');d.postType=d.postType||'Post';if(!['Post','Reel','Story','Live'].includes(d.postType))fail('Invalid post format');if(data.cricketOnly!==true)fail('Confirm this post is about cricket');d.cricketOnly=true;const account=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(user).first();d.authorName=existing?.authorName||(account?JSON.parse(account.data).name:'Cricket member');
if(d.image)fail('Upload an image for automatic safety screening instead of an external image URL');for(const k of ['url','image'])if(d[k]){let u;try{u=new URL(d[k])}catch{fail('Invalid media URL')}if(!['https:','http:'].includes(u.protocol))fail('Invalid media URL')}
if(d.mediaId){const a=await DB.prepare('SELECT * FROM assets WHERE id=? AND owner=?').bind(d.mediaId,user).first();if(!a||a.purpose==='ownership-proof')fail('Choose a public media upload you own');d.mediaMime=a.mime;if(a.mime==='application/pdf')fail('PDF files are for shipping documents, not social posts');if(d.postType==='Reel'&&!a.mime.startsWith('video/'))fail('Reels require a video upload')}
if(d.postType==='Reel'&&!d.mediaId)fail('Upload a video for your reel');if(d.postType==='Live'){d.embedUrl=streamEmbed(d.url);if(!d.embedUrl)fail('Connect a YouTube or Vimeo stream URL');d.status=['live','ended','scheduled'].includes(d.status)?d.status:'live'}
if(d.sourceMatchId){const r=await read(DB,d.sourceMatchId);if(r.type!=='matches')fail('Choose a match')}
if(data.broadcastSource!==undefined&&!['external','18-camera'].includes(data.broadcastSource))fail('Invalid broadcast source');
if(d.postType==='Live'){d.broadcastSource=existing?.broadcastSource==='18-camera'?'18-camera':data.broadcastSource||'external';if(d.broadcastSource==='18-camera'){if(!d.sourceMatchId)fail('Camera broadcasts require a match');const match=await read(DB,d.sourceMatchId);if(!await canAdminMatch(DB,match,user))fail('Only match/competition admins can publish camera broadcasts',403);if(d.status!=='ended'){const ready=await drsReadiness(DB,d.sourceMatchId);if(!ready.ready)fail('DRS is mandatory for 18-camera broadcasts: '+ready.issues.join(' '));d.drsSetupVersion=ready.setupVersion;d.drsMode='human-assisted';d.cameraSessions=ready.views.map(v=>v.sessionId)}}}
if(d.postType==='Story')d.expiresAt=(existing?.postType==='Story'?existing.expiresAt:null)||new Date(Date.now()+86400000).toISOString();if(existing?.expiresAt&&existing.expiresAt<=now())fail('This story has expired');if(existing?.performance){d.performance=existing.performance;d.sourceMatchId=existing.sourceMatchId;d.sourceVersion=existing.sourceVersion}return d}
export async function sports(request,env,path,user,body){const DB=env.DB,method=request.method;
if(path[0]==='assets'){
if(method==='POST'){if(!env.BUCKET)fail('Media storage is unavailable',503);const mime=request.headers.get('Content-Type')?.split(';')[0],allowed=['image/jpeg','image/png','image/webp','video/mp4','video/webm','application/pdf'];if(!allowed.includes(mime))fail('Use JPG, PNG, WebP, MP4, WebM or PDF');const declared=Number(request.headers.get('Content-Length'));if(declared>33554432)fail('Maximum upload is 32 MB',413);const reader=request.body?.getReader();if(!reader)fail('Empty file');let size=0,chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>33554432){await reader.cancel();fail('Maximum upload is 32 MB',413)}chunks.push(value)}if(!size)fail('Empty file');const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}const ascii=(a,b)=>String.fromCharCode(...bytes.slice(a,b));const valid=mime==='application/pdf'?ascii(0,5)==='%PDF-':mime==='image/jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:mime==='image/png'?ascii(1,4)==='PNG'&&bytes[0]===137:mime==='image/webp'?ascii(0,4)==='RIFF'&&ascii(8,12)==='WEBP':mime==='video/mp4'?ascii(4,8)==='ftyp':bytes[0]===26&&bytes[1]===69&&bytes[2]===223&&bytes[3]===163;if(!valid)fail('File contents do not match the selected media type');const purpose=request.headers.get('X-Upload-Purpose')==='ownership-proof'?'ownership-proof':mime==='application/pdf'?'carrier-document':'media';if(purpose==='ownership-proof'&&!await DB.prepare('SELECT owner FROM accounts WHERE owner=?').bind(user).first())fail('Complete account registration before uploading private ownership proof',403);if(purpose==='ownership-proof'&&size>10485760)fail('Proof documents must be 10 MB or smaller',413);if(purpose==='ownership-proof'&&!['application/pdf','image/png','image/jpeg'].includes(mime))fail('Ownership evidence must be a PDF, PNG or JPG');if(purpose==='media'){if(mime.startsWith('video/'))fail('Video uploads are rejected until automatic video safety screening is connected',415);await moderateImage(env,mime,bytes)}else if(mime==='application/pdf')checkText(new TextDecoder().decode(bytes));const id=crypto.randomUUID(),key='media/'+id;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});try{await DB.batch([DB.prepare('INSERT INTO assets(id,owner,key,mime,purpose,size,created) VALUES(?,?,?,?,?,?,?)').bind(id,user,key,mime,purpose,size,now()),contentReviewStatement(DB,id,'asset',user)])}catch(e){await env.BUCKET.delete(key);throw e}return json({id,mime,size,moderationStatus:purpose==='ownership-proof'?'private-evidence':'approved',purpose},201)}
if(method==='GET'||method==='HEAD'){const a=await DB.prepare('SELECT * FROM assets WHERE id=?').bind(path[1]).first();if(!a)fail('File not found',404);if(a.owner!==user&&!admin(request,env)){if(a.purpose==='ownership-proof')fail('Ownership proof is private to its uploader and platform verifier',403);if(!await contentApproved(DB,a.id))fail('Upload is awaiting content safety review',403);const rows=(await DB.prepare("SELECT records.data FROM records LEFT JOIN content_reviews ON content_reviews.id=records.id WHERE records.type='community' AND (content_reviews.status IS NULL OR content_reviews.status!='rejected')").all()).results;const shared=rows.some(r=>{const d=JSON.parse(r.data);return d.mediaId===a.id&&(!d.expiresAt||d.expiresAt>now())});const products=(await DB.prepare("SELECT data FROM records WHERE type='marketplace'").all()).results;const productShared=products.some(r=>JSON.parse(r.data).mediaId===a.id);const orders=(await DB.prepare('SELECT data FROM commerce_orders WHERE buyer=? OR seller=?').bind(user,user).all()).results;const documentShared=orders.some(r=>{const d=JSON.parse(r.data);return d.shipping?.labelAssetId===a.id||d.return?.labelAssetId===a.id});const jobs=(await DB.prepare('SELECT data FROM delivery_jobs WHERE buyer=? OR seller=? OR rider=?').bind(user,user,user).all()).results;const proofShared=jobs.some(r=>JSON.parse(r.data).proofPhotoId===a.id);const repairRows=(await DB.prepare('SELECT data FROM repair_orders WHERE owner=? OR provider=?').bind(user,user).all()).results;const repairShared=repairRows.some(r=>{const d=JSON.parse(r.data);return d.shipping?.inbound?.labelAssetId===a.id||d.shipping?.return?.labelAssetId===a.id});if(!repairShared&&!shared&&!productShared&&!documentShared&&!proofShared)fail('File not shared',403)}if(!env.BUCKET)fail('Media storage is unavailable',503);let range=null,start=0,end=a.size-1;const rh=request.headers.get('Range');if(rh){const m=rh.match(/^bytes=(\d*)-(\d*)$/);if(!m||(!m[1]&&!m[2]))return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+a.size}});start=m[1]?Number(m[1]):Math.max(0,a.size-Number(m[2]));end=m[1]&&m[2]?Math.min(Number(m[2]),a.size-1):a.size-1;if(start>end||start>=a.size)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+a.size}});range={offset:start,length:end-start+1}}const headers={'Content-Type':a.mime,'Content-Length':String(end-start+1),'Accept-Ranges':'bytes','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'};if(a.mime==='application/pdf')headers['Content-Disposition']='attachment; filename="carrier-label.pdf"';if(range)headers['Content-Range']=`bytes ${start}-${end}/${a.size}`;if(method==='HEAD')return new Response(null,{status:range?206:200,headers});const f=await env.BUCKET.get(a.key,range?{range}:undefined);if(!f)fail('File not found',404);return new Response(f.body,{status:range?206:200,headers})}
}
if(['match-setup','scorecard','performance','performance-share'].includes(path[0])){const r=await read(DB,path[1]);if(r.type!=='matches')fail('Not a match');let d=JSON.parse(r.data);
if(path[0]==='match-setup'&&method==='POST'){own(r,user);const b=await body();if(b.version!==r.version)fail('Match changed. Refresh.',409);if((d.events||[]).some(e=>e.eventType!=='select'))fail('Player attribution must be configured before scoring. Existing scores are preserved.');const squads={A:[],B:[]},seen=new Set();for(const side of ['A','B']){if(!Array.isArray(b.squads?.[side])||b.squads[side].length<2||b.squads[side].length>11)fail('Choose 2–11 players for each squad');for(const pid of b.squads[side]){if(seen.has(pid))fail('A player cannot appear twice or on both teams');seen.add(pid);const p=await read(DB,pid);if(p.type!=='players')fail('Choose player profiles');const profile=JSON.parse(p.data);squads[side].push({id:p.id,name:profile.name,...Object.fromEntries(['role','batting','bowling'].filter(k=>profile[k]).map(k=>[k,profile[k]]))})}}const cap=Number(b.maxBowlerOvers||Math.ceil(Number(d.overs)/5));if(!Number.isInteger(cap)||cap<1||cap>Number(d.overs))fail('Invalid bowler over limit');if(cap*squads.A.length<Number(d.overs)||cap*squads.B.length<Number(d.overs))fail('Squad and bowler limit cannot cover the scheduled overs');const setupInput=b.matchSetup||d.scoringConfig?.matchSetup;const matchSetup=setupInput?validateMatchSetup(setupInput,squads):undefined;const details={};if(b.details){for(const k of ['name','location','date','time','format']){if(typeof b.details[k]!=='string'||b.details[k].length>200)fail('Invalid match '+k);details[k]=b.details[k].trim();}if(!details.name)fail('Match name required');if(details.date&&!/^\d{4}-\d{2}-\d{2}$/.test(details.date))fail('Invalid match date');if(details.time&&!/^\d{2}:\d{2}$/.test(details.time))fail('Invalid start time');}d={...d,...details,proScoring:true,squads,scoringConfig:{maxBowlerOvers:cap,freeHit:b.freeHit!==false,widePenalty:1,noBallPenalty:1,...(matchSetup?{matchSetup}:{})},events:[]};if(b.opening){try{d=appendCommand(d,{command:'select',...b.opening});}catch(err){fail(err.message)}}if(d.tournamentId||d.leagueId)return proposeChange(DB,r,user,{kind:'setup',data:d,version:r.version});await save(DB,r,d);return json({ok:true})}
if(!d.proScoring)fail('Set up player-attributed scoring first');
if(path[0]==='scorecard'&&method==='GET')return json({id:r.id,version:r.version,name:d.name,teamA:d.teamA,teamB:d.teamB,location:d.location,date:d.date,time:d.time,format:d.format,squads:d.squads,overs:d.overs,scoringConfig:d.scoringConfig,events:d.events||[],proScoring:!!d.proScoring,score:calculateMatch(d)});
if(path[0]==='performance'&&method==='GET'){const p=playerPerformance(d,new URL(request.url).searchParams.get('playerId'));if(!p)fail('Player not in this match');return json({...p,sourceMatchId:r.id,sourceVersion:r.version})}
if(path[0]==='performance-share'&&method==='POST'){const b=await body();const player=await read(DB,b.playerId);if(player.type!=='players'||player.owner!==user&&r.owner!==user)fail('Share your own performance or a match you score',403);const p=playerPerformance(d,b.playerId);if(!p)fail('Player not in this match');if(!['Post','Story'].includes(b.destination))fail('Choose feed or story');const account=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(user).first();const key=crypto.randomUUID(),data={authorName:account?JSON.parse(account.data).name:'Cricket member',name:p.name+' • Match performance',bio:String(b.caption||'').slice(0,4000),postType:b.destination,cricketOnly:true,performance:p,sourceMatchId:r.id,sourceVersion:r.version,...(b.destination==='Story'?{expiresAt:new Date(Date.now()+86400000).toISOString()}: {})};await DB.batch([DB.prepare('INSERT INTO records(id,type,owner,data,created) VALUES(?,?,?,?,?)').bind(key,'community',user,JSON.stringify(data),now()),contentReviewStatement(DB,key,'record',user)]);return json({id:key,performance:p},201)}
}
return null}
