import {competitionAdmin} from './governance.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
const text=(v,label,max=500)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail('Enter '+label);return v.trim()};
const rows=async(DB,sql,...args)=>(await DB.prepare(sql).bind(...args).all()).results;
const record=async(DB,id,type)=>{const r=await DB.prepare('SELECT * FROM records WHERE id=?').bind(id).first();if(!r||r.type!==type)fail(type+' not found',404);return {...r,details:JSON.parse(r.data)}};
export const memberOf=(d,u)=>d.members.find(m=>m.userId===u&&m.status==='active');
export const manages=(d,u)=>!!memberOf(d,u)&&['owner','captain'].includes(memberOf(d,u).role);
function matchClock(f){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:f.timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(f.startsAt));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return {date:p.year+'-'+p.month+'-'+p.day,time:p.hour+':'+p.minute};}
const freshCall=c=>Date.parse(c.updated)>Date.now()-90000;
const liveParticipants=d=>d.participants.filter(p=>p.state==='joined'&&Date.parse(p.seen)>Date.now()-45000);
export function validateFixture(b,d){
 const x={id:b.id?text(b.id,'fixture ID',100):uuid(),title:text(b.title,'match title',160),opponentTeamId:text(b.opponentTeamId,'opponent team',100),startsAt:text(b.startsAt,'start date and time',40),reportAt:text(b.reportAt,'reporting date and time',40),timeZone:text(b.timeZone,'time zone',80),venue:text(b.venue,'ground / meeting address',300),overs:Number(b.overs),competitionId:b.competitionId?text(b.competitionId,'competition ID',100):'',notes:String(b.notes||'').slice(0,2000),lineup:b.lineup||[],duties:b.duties||[]};
 try{new Intl.DateTimeFormat('en',{timeZone:x.timeZone});}catch{fail('Choose a valid IANA time zone')}
 for(const k of ['startsAt','reportAt'])if(!/T.*(?:Z|[+-]\d\d:\d\d)$/.test(x[k])||!Number.isFinite(Date.parse(x[k])))fail('Use a date and time with its UTC offset');
 if(Date.parse(x.reportAt)>Date.parse(x.startsAt))fail('Reporting time must be before the game');
 if(!Number.isInteger(x.overs)||x.overs<1||x.overs>50)fail('Overs must be 1–50');
 if(!Array.isArray(x.lineup)||x.lineup.length>30||new Set(x.lineup).size!==x.lineup.length||x.lineup.some(u=>!memberOf(d,u)))fail('Select active squad members only');
 if(!Array.isArray(x.duties)||x.duties.length>30||x.duties.some(v=>!x.lineup.includes(v.userId)||typeof v.task!=='string'||!v.task.trim()||v.task.length>200))fail('Assign valid duties to selected players');
 return x;
}
async function hub(DB,id,user,requireActive=true){const team=await record(DB,id,'teams');const ownerAccount=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(team.owner).first();let r=await DB.prepare('SELECT * FROM team_hubs WHERE team_id=?').bind(id).first();let d=r?JSON.parse(r.data):{members:[{userId:team.owner,name:ownerAccount?JSON.parse(ownerAccount.data).name:team.details.name+' captain',role:'owner',status:'active'}],fixtures:[],responses:{}};if(requireActive&&!memberOf(d,user))fail('Active team membership required',403);return {team,r,d,version:r?.version||0};}
function notify(DB,owner,teamId,data,stamp=now(),guard=null){let sql='INSERT INTO team_notifications(id,owner,team_id,data,created) SELECT ?,?,?,?,?';const args=[uuid(),owner,teamId,JSON.stringify(data),stamp];if(guard){sql+=' WHERE EXISTS(SELECT 1 FROM team_hubs WHERE team_id=? AND json_extract(data,\'$.revisionKey\')=?)';args.push(teamId,guard);}return DB.prepare(sql).bind(...args);}
async function commit(DB,h,user,d,b,kind,note,extraRecipients=[],extra=[]){
 if(b.version!==h.version)fail('Team changed. Refresh before saving.',409);const key=uuid(),stamp=now();d.revisionKey=key;let q=h.r?DB.prepare('UPDATE team_hubs SET data=?,version=version+1,updated=? WHERE team_id=? AND version=?').bind(JSON.stringify(d),stamp,h.team.id,h.version):DB.prepare('INSERT OR IGNORE INTO team_hubs(team_id,data,updated) VALUES(?,?,?)').bind(h.team.id,JSON.stringify(d),stamp);
 if(h.conditions?.length){const condition=h.conditions.map(c=>'EXISTS(SELECT 1 FROM records WHERE id=\''+c.id.replaceAll("'","''")+'\' AND version='+Number(c.version)+')').join(' AND ');if(h.r){q=DB.prepare('UPDATE team_hubs SET data=?,version=version+1,updated=? WHERE team_id=? AND version=? AND '+condition).bind(JSON.stringify(d),stamp,h.team.id,h.version);}else{q=DB.prepare('INSERT OR IGNORE INTO team_hubs(team_id,data,updated) SELECT ?,?,? WHERE '+condition).bind(h.team.id,JSON.stringify(d),stamp);}}
 const guard='EXISTS(SELECT 1 FROM team_hubs WHERE team_id=? AND json_extract(data,\'$.revisionKey\')=?)';
 const recipients=[...new Set([...h.d.members.filter(m=>m.status==='active').map(m=>m.userId),...d.members.filter(m=>m.status==='active').map(m=>m.userId),...extraRecipients])];
 const results=await DB.batch([q,DB.prepare('INSERT INTO team_events(id,team_id,actor,kind,data,created) SELECT ?,?,?,?,?,? WHERE '+guard).bind(uuid(),h.team.id,user,kind,JSON.stringify({note,fixtureId:b.fixture?.id||b.fixtureId||null}),stamp,h.team.id,key),...recipients.map(u=>notify(DB,u,h.team.id,{kind,title:note,actor:user,fixtureId:b.fixtureId||b.fixture?.id||null},stamp,key)),...extra.map(fn=>fn(guard,h.team.id,key))]);
 if(!results[0].meta.changes)fail('Team changed. Refresh before saving.',409);return json({ok:true,version:h.version+1});
}
export async function teamHuddle(request,env,path,user,body){if(path[0]!=='huddle')return null;const DB=env.DB,method=request.method;
 if(path[1]==='proposals'&&method==='GET'){const items=[];for(const r of await rows(DB,'SELECT * FROM team_hubs')){const d=JSON.parse(r.data);for(const f of d.fixtures)if(f.status==='pending_approval'&&await competitionAdmin(DB,f.competitionId,user))items.push({teamId:r.team_id,version:r.version,fixture:f});}return json(items);}
 if(path[1]==='notifications'){
  if(method==='GET'){const all=await rows(DB,'SELECT * FROM team_notifications WHERE owner=? ORDER BY created DESC LIMIT 100',user);const unread=await DB.prepare('SELECT COUNT(*) AS n FROM team_notifications WHERE owner=? AND read_at IS NULL').bind(user).first();return json({unread:unread.n,notifications:all.map(r=>({...JSON.parse(r.data),id:r.id,teamId:r.team_id,created:r.created,read:!!r.read_at})),delivery:'in-app polling; background push not configured'});}
  if(method==='POST'){const b=await body();await DB.prepare('UPDATE team_notifications SET read_at=? WHERE owner=? AND id=?').bind(now(),user,text(b.id,'notification ID',100)).run();return json({ok:true});}
 }
 if(!path[1]&&method==='GET'){const teams=await rows(DB,"SELECT r.id,r.owner,r.data,h.data AS hub_data,h.version FROM records r LEFT JOIN team_hubs h ON h.team_id=r.id WHERE r.type='teams'");return json({teams:teams.filter(r=>r.owner===user||(r.hub_data&&JSON.parse(r.hub_data).members.some(m=>m.userId===user&&['active','invited'].includes(m.status)))).map(r=>({id:r.id,name:JSON.parse(r.data).name,version:r.version||0,status:r.owner===user?'active':JSON.parse(r.hub_data).members.find(m=>m.userId===user).status})),callingConfigured:!!env.TEAM_TURN_URL&&!!env.TEAM_TURN_SECRET});}
 const h=await hub(DB,path[1],user,false),d=structuredClone(h.d),me=memberOf(d,user),manager=manages(d,user),member=d.members.find(m=>m.userId===user);
 if(path.length===2&&method==='GET'){
  if(!me){if(member?.status==='invited')return json({team:{id:h.team.id,name:h.team.details.name},version:h.version,invitation:true});fail('Active team membership required',403);}
  const events=await rows(DB,'SELECT * FROM team_events WHERE team_id=? ORDER BY created DESC LIMIT 80',h.team.id);
  const messages=await rows(DB,'SELECT * FROM team_messages WHERE team_id=? AND (recipient IS NULL OR recipient=? OR sender=?) ORDER BY created DESC LIMIT 100',h.team.id,user,user);
  const calls=await rows(DB,'SELECT * FROM team_calls WHERE team_id=? ORDER BY created DESC LIMIT 20',h.team.id);
  // Expired ETAs are not exposed, even if a browser has gone offline.
  for(const response of Object.values(d.responses||{}))for(const v of Object.values(response))if(v.etaExpiresAt&&Date.parse(v.etaExpiresAt)<Date.now()){delete v.eta;delete v.etaExpiresAt;}
  delete d.revisionKey;
  return json({team:{id:h.team.id,name:h.team.details.name},version:h.version,...d,manager,events:events.map(r=>({id:r.id,kind:r.kind,...JSON.parse(r.data),created:r.created})),messages:messages.reverse(),calls:calls.filter(c=>freshCall(c)&&JSON.parse(c.data).participants.some(p=>p.userId===user&&['invited','joined'].includes(p.state))).map(c=>({id:c.id,version:c.version,...JSON.parse(c.data),live:liveParticipants(JSON.parse(c.data))})),callingConfigured:!!env.TEAM_TURN_URL&&!!env.TEAM_TURN_SECRET});
 }
 if(path[2]==='invitation'&&method==='POST'){const b=await body();if(member?.status!=='invited')fail('No pending invitation',403);if(!['accept','decline'].includes(b.action))fail('Choose accept or decline');d.members.find(m=>m.userId===user).status=b.action==='accept'?'active':'declined';return commit(DB,h,user,d,b,'invitation',member.name+' '+(b.action==='accept'?'joined the team':'declined the invitation'),[user]);}
 if(!me&&!(path[2]==='fixtures'&&method==='POST'))fail('Active team membership required',403);
 if(path[2]==='members'&&method==='POST'){
  if(!manager)fail('Captain permissions required',403);const b=await body();
  if(b.action==='invite'){const p=await record(DB,b.playerId,'players');const a=await DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(p.owner).first();if(!a)fail('Player must complete platform registration');if(d.members.filter(m=>['active','invited'].includes(m.status)).length>=100)fail('Squad limit is 100');if(d.members.some(m=>m.userId===p.owner&&['active','invited'].includes(m.status)))fail('Player already belongs to this squad or has an invitation',409);d.members=d.members.filter(m=>m.userId!==p.owner);d.members.push({userId:p.owner,playerId:p.id,name:p.details.name,role:'player',status:'invited',invitedAt:now()});return commit(DB,h,user,d,b,'squad_invite',p.details.name+' was invited to '+h.team.details.name,[p.owner]);}
  const target=d.members.find(m=>m.userId===b.userId);if(!target||target.role==='owner')fail('Choose a squad member other than the team owner');
  if(b.action==='remove'){target.status='removed';for(const f of d.fixtures){f.lineup=f.lineup.filter(u=>u!==target.userId);f.duties=f.duties.filter(v=>v.userId!==target.userId);}for(const r of Object.values(d.responses||{}))delete r[target.userId];return commit(DB,h,user,d,b,'squad_remove',target.name+' was removed from the squad',[target.userId]);}
  if(b.action==='role'){if(h.team.owner!==user)fail('Only the team owner can appoint captains',403);if(!memberOf(d,target.userId)||!['captain','vice_captain','wicketkeeper','player'].includes(b.role))fail('Choose an active player and valid role');target.role=b.role;return commit(DB,h,user,d,b,'role',target.name+' is now '+b.role.replaceAll('_',' '));}fail('Unknown squad action');
 }
 if(path[2]==='fixtures'&&method==='POST'){
  const b=await body(),previous=d.fixtures.find(f=>f.id===b.fixture?.id);if(!manager&&!(previous?.competitionId&&await competitionAdmin(DB,previous.competitionId,user)))fail('Captain permissions required',403);
  if(b.action==='approve'){
   if(!previous||previous.status!=='pending_approval'||!previous.competitionId||!await competitionAdmin(DB,previous.competitionId,user))fail('Competition administrator approval required',403);
   previous.status='scheduled';
  }else{if(!manager)fail('Captain permissions required',403);const f=validateFixture(b.fixture,d);if(f.opponentTeamId===h.team.id)fail('Choose a different opponent');await record(DB,f.opponentTeamId,'teams');if(previous&&previous.competitionId!==f.competitionId)fail('Competition scope cannot change');if(d.fixtures.length>=100&&!previous)fail('Archive is limited to 100 fixtures per team');if(f.competitionId){const c=await DB.prepare('SELECT type FROM records WHERE id=?').bind(f.competitionId).first();if(!c||!['leagues','tournaments'].includes(c.type))fail('Choose a real tournament or league');}if(b.action==='cancel'&&f.competitionId&&!await competitionAdmin(DB,f.competitionId,user))fail('Ask the competition administrator to cancel an approved competition fixture.',403);f.status=b.action==='cancel'?'cancelled':f.competitionId?'pending_approval':'scheduled';if(previous?.matchId)f.matchId=previous.matchId;if(previous)Object.assign(previous,f);else d.fixtures.push(f);}
  const f=d.fixtures.find(f=>f.id===(b.fixture?.id||previous?.id))||d.fixtures.at(-1);const extra=[];
  // Approved fixture edits preserve scorecards and use the current match version.
  if(f.matchId){const r=await record(DB,f.matchId,'matches');h.conditions=[{id:r.id,version:r.version}];if((r.details.events||[]).some(e=>e.eventType!=='select'))fail('Scoring has started. Use competition correction workflow; no schedule or squad reset is permitted.',409);if(r.details.proScoring&&f.overs!==r.details.overs)fail('Overs are locked after scoring setup.',409);if(f.status!=='pending_approval'){const md={...r.details,name:f.title,overs:f.overs,...matchClock(f),scheduledAt:f.startsAt,timeZone:f.timeZone,location:f.venue,fixtureStatus:f.status};extra.push((guard,teamId,key)=>DB.prepare('UPDATE records SET data=?,version=version+1 WHERE id=? AND version=? AND '+guard).bind(JSON.stringify(md),r.id,r.version,teamId,key));}}
  else if(f.status==='scheduled'){const opp=await record(DB,f.opponentTeamId,'teams');f.matchId=uuid();const comp=f.competitionId?await DB.prepare('SELECT type FROM records WHERE id=?').bind(f.competitionId).first():null;const md={name:f.title,teamA:h.team.details.name,teamB:opp.details.name,teamAId:h.team.id,teamBId:opp.id,overs:f.overs,...matchClock(f),scheduledAt:f.startsAt,timeZone:f.timeZone,location:f.venue,events:[],huddleFixtureId:f.id,...(comp?{[comp.type==='leagues'?'leagueId':'tournamentId']:f.competitionId}:{})};extra.push((guard,teamId,key)=>DB.prepare('INSERT INTO records(id,type,owner,data,created) SELECT ?,?,?,?,? WHERE '+guard).bind(f.matchId,'matches',h.team.owner,JSON.stringify(md),now(),teamId,key));}
  let admins=[];if(f.status==='pending_approval'){const c=await DB.prepare('SELECT owner FROM records WHERE id=?').bind(f.competitionId).first();admins=[c.owner,...(await rows(DB,'SELECT owner FROM competition_admins WHERE competition_id=?',f.competitionId)).map(x=>x.owner)];}
  return commit(DB,h,user,d,b,'fixture',f.title+': '+f.status.replaceAll('_',' ')+' / squad or schedule updated',admins,extra);
 }
 if(path[2]==='response'&&method==='POST'){const b=await body(),f=d.fixtures.find(f=>f.id===b.fixtureId);if(!f||f.status==='cancelled')fail('Choose an active fixture');if(!['available','unavailable','maybe','on_the_way','arrived'].includes(b.status))fail('Choose availability or arrival status');const v={status:b.status,note:String(b.note||'').slice(0,300),updated:now()};if(b.eta){if(typeof b.eta!=='string'||!Number.isFinite(Date.parse(b.eta))||Date.parse(b.eta)<Date.now()-60000||Date.parse(b.eta)>Date.now()+86400000)fail('ETA must be within the next 24 hours');v.eta=new Date(b.eta).toISOString();v.etaExpiresAt=new Date(Math.min(Date.parse(b.eta)+3600000,Date.now()+86400000)).toISOString();}d.responses[b.fixtureId]??={};d.responses[b.fixtureId][user]=v;return commit(DB,h,user,d,b,'availability',me.name+': '+b.status.replaceAll('_',' '));}
 if(path[2]==='messages'&&method==='POST'){
  const b=await body(),msg=text(b.body,'message',2000),kind=b.kind==='announcement'?'announcement':'message',recipient=b.recipient||null;if(kind==='announcement'&&!manager)fail('Only captains can publish announcements',403);if(recipient&&!memberOf(d,recipient))fail('Recipient must be an active teammate');if(b.fixtureId&&!d.fixtures.some(f=>f.id===b.fixtureId))fail('Fixture not found');const since=new Date(Date.now()-60000).toISOString();const stamp=now(),id=uuid();const q=DB.prepare('INSERT INTO team_messages(id,team_id,sender,recipient,fixture_id,kind,body,created) SELECT ?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM team_messages WHERE sender=? AND created>?)<30 AND (EXISTS(SELECT 1 FROM team_hubs WHERE team_id=? AND version=?) OR (?=0 AND NOT EXISTS(SELECT 1 FROM team_hubs WHERE team_id=?)))').bind(id,h.team.id,user,recipient,b.fixtureId||null,kind,msg,stamp,user,since,h.team.id,h.version,h.version,h.team.id);
  const targets=recipient?[recipient]:d.members.filter(m=>m.status==='active'&&m.userId!==user).map(m=>m.userId);
  const results=await DB.batch([q,...targets.map(u=>DB.prepare('INSERT INTO team_notifications(id,owner,team_id,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM team_messages WHERE id=?)').bind(uuid(),u,h.team.id,JSON.stringify({kind,title:me.name+(kind==='announcement'?' posted an announcement':' sent a message'),fixtureId:b.fixtureId||null}),stamp,id))]);if(!results[0].meta.changes)fail('Team changed or message limit reached. Refresh before retrying.',409);return json({id},201);
 }
 if(path[2]==='calls')return callApi(DB,env,h,user,path,method,body,request);
 return json({error:'Team Huddle endpoint not found'},404);
}
async function iceConfig(env,user){if(!env.TEAM_TURN_URL||!env.TEAM_TURN_SECRET)fail('Voice calling needs the platform TURN relay configured first.',503);const urls=String(env.TEAM_TURN_URL).split(',').map(s=>s.trim());if(urls.some(u=>!/^turns?:[^\s]+$/.test(u)))fail('Invalid voice relay configuration',503);const username=Math.floor(Date.now()/1000+3600)+':'+user;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.TEAM_TURN_SECRET),{name:'HMAC',hash:'SHA-1'},false,['sign']);const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(username)));return {iceServers:[{urls,username,credential:btoa(String.fromCharCode(...bytes))}],iceTransportPolicy:'relay'};}
export async function callApi(DB,env,h,user,path,method,body,request){
 if(path.length===3&&method==='POST'){await iceConfig(env,user);const b=await body();if(b.consent!==true)fail('Confirm microphone and call consent');if(!Array.isArray(b.recipients)||!b.recipients.length||b.recipients.length>5||new Set(b.recipients).size!==b.recipients.length||b.recipients.some(u=>u===user||!memberOf(h.d,u)))fail('Choose 1–5 active teammates');const busy=await rows(DB,'SELECT data,updated FROM team_calls WHERE team_id=? AND updated>?',h.team.id,new Date(Date.now()-90000).toISOString());if(busy.some(c=>JSON.parse(c.data).participants.some(p=>[user,...b.recipients].includes(p.userId)&&['invited','joined'].includes(p.state))))fail('A selected teammate already has an active or ringing call',409);const stamp=now(),id=uuid(),data={host:user,participants:[{userId:user,state:'joined',seen:stamp},...b.recipients.map(u=>({userId:u,state:'invited',seen:stamp}))],recording:false};await DB.batch([DB.prepare('INSERT INTO team_calls(id,team_id,data,created,updated) VALUES(?,?,?,?,?)').bind(id,h.team.id,JSON.stringify(data),stamp,stamp),...b.recipients.map(u=>notify(DB,u,h.team.id,{kind:'call',title:memberOf(h.d,user).name+' is calling',callId:id},stamp))]);return json({id},201);}
 const r=await DB.prepare('SELECT * FROM team_calls WHERE id=? AND team_id=?').bind(path[3],h.team.id).first();if(!r)fail('Call not found',404);const d=JSON.parse(r.data),p=d.participants.find(p=>p.userId===user);if(!p)fail('You were not invited to this call',403);if(!freshCall(r)||p.state==='invited'&&Date.parse(p.seen)<Date.now()-90000)fail('Call expired',410);
 if(method==='GET'){if(!['invited','joined'].includes(p.state))fail('Call ended',410);if(path[4]==='signals'){if(p.state!=='joined')fail('Join first',403);const cursor=Number(new URL(request.url).searchParams.get('after')||0);if(!Number.isSafeInteger(cursor)||cursor<0)fail('Invalid signal cursor');return json(await rows(DB,'SELECT id,sender,data FROM team_signals WHERE call_id=? AND recipient=? AND id>? ORDER BY id LIMIT 200',r.id,user,cursor));}return json({id:r.id,version:r.version,...d,live:liveParticipants(d).filter(p=>memberOf(h.d,p.userId)),ice:p.state==='joined'?await iceConfig(env,user):null});}
 if(path[4]==='signals'){
  if(p.state!=='joined')fail('Join the call before signaling',403);
  if(method==='POST'){const b=await body();if(!d.participants.some(v=>v.userId===b.recipient&&v.state==='joined')||!memberOf(h.d,b.recipient)||b.recipient===user)fail('Recipient is not in the call');if(!['offer','answer','ice'].includes(b.signal?.type)||JSON.stringify(b.signal).length>20000)fail('Invalid call signal');const rate=await DB.prepare('SELECT COUNT(*) AS n FROM team_signals WHERE call_id=? AND sender=? AND created>?').bind(r.id,user,new Date(Date.now()-60000).toISOString()).first();if(rate.n>=150)fail('Too many call signals',429);await DB.prepare('INSERT INTO team_signals(call_id,sender,recipient,data,created) VALUES(?,?,?,?,?)').bind(r.id,user,b.recipient,JSON.stringify(b.signal),now()).run();return json({ok:true});}
 }
 if(method==='POST'){const b=await body();if(b.version!==r.version)fail('Call changed. Refresh.',409);if(!['join','leave','heartbeat','end'].includes(b.action))fail('Invalid call action');if(b.action==='join'){if(p.state!=='invited'||b.consent!==true)fail('Accept the invitation and microphone consent',403);p.state='joined';}else if(b.action==='leave'){p.state='left';}else if(b.action==='end'){if(d.host!==user)fail('Only the host can end everyone’s call',403);d.participants.forEach(v=>v.state='left');}else if(p.state!=='joined')fail('Join first',403);p.seen=now();const x=await DB.prepare('UPDATE team_calls SET data=?,version=version+1,updated=? WHERE id=? AND version=?').bind(JSON.stringify(d),now(),r.id,r.version).run();if(!x.meta.changes)fail('Call changed. Refresh.',409);return json({ok:true});}
 return json({error:'Call endpoint not found'},404);
}
