import {admin} from './payments.js';
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}),fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},now=()=>new Date().toISOString();
export const FEEDBACK_CATEGORIES=['Platform review','Feature suggestion','Bug report','Usability & design','Scoring experience','Marketplace','Bookings & facilities','Athlete Fuel','PitchRush','18Digital','Other'];
export const FEEDBACK_STATUSES=['new','reviewed','planned','in_progress','resolved','closed'];
const text=(v,name,max,required=true)=>{if(v===undefined&&!required)return '';if(typeof v!=='string'||v.length>max||required&&!v.trim())fail('Enter '+name+' (up to '+max+' characters)');return v.trim()};
function view(r,isAdmin){return {...JSON.parse(r.data),id:r.id,status:r.status,version:r.version,created:r.created,updated:r.updated,...(isAdmin?{owner:r.owner,email:r.email,internalNote:r.internal_note||''}:{})}}
export async function thirdUmpire(request,env,path,user,body){if(path[0]!=='feedback')return null;const DB=env.DB,isAdmin=admin(request,env),method=request.method;
 if(method==='GET'&&!path[1]){const rows=(await DB.prepare('SELECT * FROM platform_feedback WHERE owner=? ORDER BY created DESC LIMIT 100').bind(user).all()).results;return json({name:'18’s Third Umpire',categories:FEEDBACK_CATEGORIES,statuses:FEEDBACK_STATUSES,reviews:rows.map(r=>view(r,false)),isAdmin,emailDeliveryEnabled:false,privacy:'Private platform feedback, visible only to you and platform operations. No public reviews or rating averages are created.'})}
 if(path[1]==='inbox'&&method==='GET'){if(!isAdmin)fail('Platform administrator required',403);const params=new URL(request.url).searchParams,status=params.get('status')||'',offset=Number(params.get('offset')||0);if(status&&!FEEDBACK_STATUSES.includes(status)||!Number.isInteger(offset)||offset<0||offset>100000)fail('Invalid inbox filter');const rows=(await DB.prepare('SELECT * FROM platform_feedback WHERE (?=? OR status=?) ORDER BY created DESC LIMIT 100 OFFSET ?').bind(status,'',status,offset).all()).results;return json({reviews:rows.map(r=>view(r,true)),offset,nextOffset:rows.length===100?offset+100:null,emailDeliveryEnabled:false})}
 if(method==='POST'&&!path[1]){const b=await body();if(b.privacyAccepted!==true)fail('Accept the private feedback notice');if(!FEEDBACK_CATEGORIES.includes(b.category))fail('Choose a feedback category');if(b.rating!==null&&b.rating!==undefined&&(!Number.isInteger(b.rating)||b.rating<1||b.rating>5))fail('Rating must be 1–5 or left blank');if(typeof b.submissionKey!=='string'||!/^[a-zA-Z0-9-]{16,80}$/.test(b.submissionKey))fail('Invalid submission key');const existing=await DB.prepare('SELECT id FROM platform_feedback WHERE owner=? AND submission_key=?').bind(user,b.submissionKey).first();if(existing)return json({id:existing.id,saved:true,duplicate:true,emailSent:false});const consent=b.replyConsent===true,email=consent?request.headers.get('oai-authenticated-user-email'):null;if(consent&&!email)fail('A verified account email is required for follow-up',401);const data={category:b.category,rating:b.rating??null,title:text(b.title,'feedback title',140),message:text(b.message,'your review or feedback',3000),improvement:text(b.improvement,'your suggested improvement',2000,false),replyConsent:consent,privacyAccepted:true,privacyVersion:'third-umpire-private-v1',emailDeliveryStatus:'not_configured'};const id=crypto.randomUUID(),stamp=now(),since=new Date(Date.now()-86400000).toISOString();let inserted;try{inserted=await DB.prepare('INSERT INTO platform_feedback(id,owner,submission_key,email,data,created,updated) SELECT ?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM platform_feedback WHERE owner=? AND created>?)<5').bind(id,user,b.submissionKey,email,JSON.stringify(data),stamp,stamp,user,since).run()}catch(e){const duplicate=await DB.prepare('SELECT id FROM platform_feedback WHERE owner=? AND submission_key=?').bind(user,b.submissionKey).first();if(duplicate)return json({id:duplicate.id,saved:true,duplicate:true,emailSent:false});throw e}if(!inserted.meta.changes)fail('You can submit up to five feedback entries in 24 hours. Please try again later.',429);return json({id,saved:true,emailSent:false,message:'Saved privately to 18’s Third Umpire. Email delivery will be connected later.'},201)}
 if(method==='PATCH'&&path[1]){if(!isAdmin)fail('Platform administrator required',403);const b=await body();if(!FEEDBACK_STATUSES.includes(b.status)||!Number.isInteger(b.version))fail('Choose a valid review status');const note=text(b.internalNote,'internal review note',2000,false),x=await DB.prepare('UPDATE platform_feedback SET status=?,internal_note=?,version=version+1,updated=? WHERE id=? AND version=?').bind(b.status,note,now(),path[1],b.version).run();if(!x.meta.changes)fail('Feedback changed or was withdrawn. Refresh.',409);return json({ok:true})}
 if(method==='DELETE'&&path[1]){const x=await DB.prepare('DELETE FROM platform_feedback WHERE id=? AND owner=?').bind(path[1],user).run();if(!x.meta.changes)fail('Your feedback was not found',404);return json({ok:true})}
 return json({error:'Feedback endpoint not found'},404)
}
