"""18 Health Rating v1: an explainable expert system, not a trained clinical model.

Python is the model source. Export its versioned parameters to the Worker runtime:
    python3 models/health_rating.py --export
Or score structured ingredients from JSON on stdin (no network or paid API).
Weights are platform heuristics, not WHO-approved nutrient-profile thresholds.
"""
import json
import sys
from pathlib import Path

GROUPS = [
    ("Vegetables", 9, "spinach,kale,broccoli,carrot,tomato,cucumber,onion,garlic,pepper,bell pepper,capsicum,cabbage,cauliflower,peas,green peas,okra,eggplant,aubergine,beetroot,lettuce,mushroom,pumpkin,sweet potato,green beans,zucchini,courgette,celery"),
    ("Whole fruit", 8.5, "apple,banana,orange,berries,blueberry,strawberry,mango,papaya,pineapple,pear,grapes,lemon,lime,avocado,pomegranate,watermelon"),
    ("Whole grains", 8.5, "oats,rolled oats,brown rice,quinoa,millet,ragi,jowar,bajra,whole wheat,whole wheat flour,wholegrain bread,barley,bulgur"),
    ("Legumes", 9, "lentils,dal,moong dal,toor dal,chickpeas,chana,beans,kidney beans,black beans,rajma,soybeans,tofu,edamame"),
    ("Nuts and seeds", 8, "almond,almonds,walnut,walnuts,peanut,peanuts,cashew,cashews,chia seeds,flax seeds,sesame seeds,pumpkin seeds,sunflower seeds"),
    ("Protein foods", 7, "chicken,chicken breast,fish,salmon,tuna,sardines,egg,eggs,turkey,plain yogurt,plain yoghurt,greek yogurt,low fat milk"),
    ("Unsaturated oils", 6.5, "olive oil,extra virgin olive oil,canola oil,rapeseed oil,sunflower oil,soybean oil,groundnut oil,mustard oil"),
    ("Refined starches", 4.5, "white rice,rice,white flour,maida,white bread,pasta,noodles,semolina,potato,potatoes,corn starch"),
    ("Saturated-fat sources", 3, "butter,ghee,cream,coconut oil,palm oil,lard,coconut milk,cheese,paneer,whole milk"),
    ("Free-sugar sources", 2, "sugar,brown sugar,cane sugar,honey,jaggery,maple syrup,corn syrup,glucose syrup,fruit juice,apple juice,orange juice"),
    ("High-sodium ingredients", 1.5, "salt,sea salt,table salt,soy sauce,stock cube,bouillon"),
    ("Processed meat", 2.5, "bacon,sausage,salami,hot dog,ham"),
    ("Industrial trans-fat source", 0, "partially hydrogenated oil"),
    ("Seasonings", None, "turmeric,cumin,coriander,coriander powder,cinnamon,black pepper,ginger,chilli,chili,paprika,basil,parsley,mint,cardamom,clove,oregano,water"),
]
MODEL = {
    "version": "18-health-expert-2026-10-v1",
    "kind": "Python-authored expert rules; not a trained AI or clinical assessment",
    "ingredients": {name: {"group": group, "score": score} for group, score, names in GROUPS for name in names.split(",")},
    "preparationPenalties": {"Steamed": 0, "Boiled": 0, "Raw": 0, "Grilled": 0, "Baked": 0, "Stir-fried": 0.3, "Deep-fried": 1.5, "Other": 0.5},
    "nutrientPenalties": {"sodiumMg": [600, 1], "addedSugarG": [10, 1], "saturatedFatG": [5, 1]},
    "sources": ["https://www.who.int/news-room/fact-sheets/detail/healthy-diet", "https://www.ams.usda.gov/rules-regulations/organic/labeling"],
}

def normalize(name):
    name = " ".join(name.strip().lower().split())
    return name.removeprefix("organic ")

def evaluate(data):
    rows = data["ingredientRows"]
    unknown = [r["name"] for r in rows if normalize(r["name"]) not in MODEL["ingredients"]]
    scored = [(r, MODEL["ingredients"][normalize(r["name"])]) for r in rows if normalize(r["name"]) in MODEL["ingredients"]]
    mass = sum(r["grams"] for r, rule in scored if rule["score"] is not None)
    result = {"modelVersion": MODEL["version"], "score": None, "unknown": unknown, "basis": "Declared ingredient mass; neutral water/seasonings excluded"}
    if unknown or not mass:
        return result
    score = sum(r["grams"] * rule["score"] for r, rule in scored if rule["score"] is not None) / mass
    score -= MODEL["preparationPenalties"].get(data.get("preparation", "Other"), 0.5)
    for key, (threshold, penalty) in MODEL["nutrientPenalties"].items():
        if data.get("nutrition", {}).get(key, 0) > threshold:
            score -= penalty
    result["score"] = round(max(0, min(10, score)) + 1e-9, 1)
    return result

if __name__ == "__main__":
    if "--export" in sys.argv:
        out = "// Generated by models/health_rating.py --export. Do not hand-edit.\nexport const HEALTH_MODEL=" + json.dumps(MODEL, ensure_ascii=False, separators=(",", ":")) + ";\n"
        target = Path(__file__).resolve().parents[1] / "public" / "health-model.js"
        if "--check" in sys.argv:
            if not target.exists() or target.read_text() != out:
                sys.exit("Health model export is stale")
        else:
            target.write_text(out)
    else:
        print(json.dumps(evaluate(json.load(sys.stdin))))
