import test from 'node:test';
import assert from 'node:assert/strict';
import {appendCommand,calculateMatch,playerPerformance,activeEvents} from '../public/scoring-engine.js';
import {FORMATS} from '../public/cricket-formats.js';
import {nrrContribution,standings,tournamentPlan} from '../public/competition-engine.js';
const make=(format='T20',overs=FORMATS[format].overs)=>({name:'Synthetic format QA',teamA:'A',teamB:'B',format,overs,proScoring:true,squads:{A:[1,2,3,4].map(i=>({id:'a'+i,name:'A'+i})),B:[1,2,3,4].map(i=>({id:'b'+i,name:'B'+i}))},events:[],scoringConfig:{maxBowlerOvers:20,followOnLead:200}});
const command=(m,data)=>appendCommand(m,data);
function open(m){const s=calculateMatch(m).state,p=s.side==='A'?'a':'b',q=s.side==='A'?'b':'a';return command(m,{command:'select',strikerId:p+'1',nonStrikerId:p+'2',bowlerId:q+'1'});}
function finish(m,runs){m=open(m);if(runs)m=command(m,{runs,boundary:[4,6].includes(runs)?runs:0});return command(m,{command:'close',reason:'declared',note:'Synthetic umpire declaration'});}
test('T10, T20, ODI, 40 overs and custom quotas are format-aware',()=>{for(const [key,quota]of [['T10',60],['T20',120],['ODI',300],['40 overs',240],['Custom',120]])assert.equal(calculateMatch(make(key)).state.quota,quota);assert.equal(calculateMatch(make('Custom',7)).state.quota,42);});
test('Test has no limit/free hit and supports all four innings with chase results',()=>{let m=make('Test');assert.equal(calculateMatch(m).state.quota,null);m=open(m);m=command(m,{noBall:true,runs:0});assert.equal(calculateMatch(m).state.freeHit,false);assert.equal(calculateMatch(m).first.batters.a1.balls,1);m=command(m,{command:'close',reason:'declared'});m=finish(m,2);m=finish(m,4);let v=calculateMatch(m);assert.equal(v.current,4);assert.equal(v.target,4);m=open(m);m=command(m,{runs:4,boundary:4});v=calculateMatch(m);assert.equal(v.resultDetail.winner,'B');assert.equal(v.resultDetail.kind,'wickets');assert.equal(playerPerformance(m,'a1').batting.runs,4);});
test('follow-on changes innings order, validates lead and detects innings wins',()=>{let m=make('Test');m=finish(m,250);m=finish(m,40);assert.equal(calculateMatch(m).current,3);m=command(m,{command:'follow_on',note:'Official follow-on'});assert.equal(calculateMatch(m).state.side,'B');m=finish(m,100);assert.match(calculateMatch(m).result,/A won by an innings and 110 runs/);assert.throws(()=>command(m,{runs:1}),/complete/);});
test('Test draw and tie remain distinct; ordinary limited overs cannot declare/draw',()=>{let m=make('Test');m=command(m,{command:'status',status:'drawn',note:'Time expired'});assert.equal(calculateMatch(m).resultDetail.kind,'draw');let n=make('Test');n=finish(n,20);n=finish(n,20);n=finish(n,10);n=finish(n,10);assert.equal(calculateMatch(n).resultDetail.kind,'tie');assert.throws(()=>command(make(),{command:'close',reason:'declared'}),/multi-innings/);assert.throws(()=>command(make(),{command:'status',status:'drawn',note:'Bad'}),/Invalid/);});
test('no-ball counts as faced, wide does not; penalties and audit undo preserve events',()=>{let m=open(make());m=command(m,{noBall:true,runs:2});m=command(m,{runType:'wide',runs:0});let v=calculateMatch(m);assert.equal(v.first.balls,0);assert.equal(v.first.batters.a1.balls,1);assert.equal(v.first.runs,4);const size=m.events.length;m=command(m,{command:'undo'});assert.equal(m.events.length,size+1);assert.equal(activeEvents(m).length,size-1);assert.equal(calculateMatch(m).first.runs,3);});
test('100-ball uses five-ball sets, ten-ball end changes and max two consecutive sets',()=>{let m=open(make('Hundred'));for(let i=0;i<5;i++)m=command(m,{runs:0});let v=calculateMatch(m);assert.equal(v.first.balls,5);assert.equal(v.state.strikerId,'a1');m=command(m,{command:'select',strikerId:'a1',nonStrikerId:'a2',bowlerId:'b1'});for(let i=0;i<5;i++)m=command(m,{runs:0});v=calculateMatch(m);assert.equal(v.state.strikerId,'a2');assert.throws(()=>command(m,{command:'select',strikerId:'a2',nonStrikerId:'a1',bowlerId:'b1'}),/consecutive/);});
test('Super Over state stays separate, alternates sides and closes on two wickets',()=>{let m=open(make('Custom',1));m=command(m,{command:'close'});m=open(m);m=command(m,{command:'close'});assert.equal(calculateMatch(m).resultDetail.kind,'tie');m=command(m,{command:'tie_break',note:'Official tie-break'});assert.equal(calculateMatch(m).state.side,'B');m=open(m);m=command(m,{dismissal:'bowled'});m=command(m,{command:'select',strikerId:'b3',nonStrikerId:'b2',bowlerId:'a1'});m=command(m,{dismissal:'caught',fielderId:'a2'});assert.equal(calculateMatch(m).current,4);m=open(m);m=command(m,{runs:4,boundary:4});assert.equal(calculateMatch(m).resultDetail.winner,'A');assert.equal(playerPerformance(m,'a1').batting.runs,0);});
test('five-run post-result correction recomputes winner and can be undone without deleting',()=>{let m=open(make('Custom',1));m=command(m,{runs:4,boundary:4});m=command(m,{command:'close'});m=open(m);m=command(m,{runs:6,boundary:6});assert.equal(calculateMatch(m).resultDetail.winner,'B');m=command(m,{command:'penalty',runs:5,beneficiary:1,note:'Official retroactive award'});assert.equal(calculateMatch(m).result,null);m=command(m,{command:'undo'});assert.equal(calculateMatch(m).resultDetail.winner,'B');});
test('NRR uses full quota for all out, adjusted DLS contribution and excludes tie-break/Test',()=>{let m=open(make('Custom',20));m=command(m,{runs:10});for(let i=0;i<3;i++){m=command(m,{dismissal:'bowled'});if(i<2)m=command(m,{command:'select',strikerId:'a'+(i+3),nonStrikerId:'a2',bowlerId:'b1'});}m=open(m);m=command(m,{runs:6,boundary:6});m=command(m,{runs:6,boundary:6});let n=nrrContribution(m);assert.equal(n.A.ballsFor,120);assert.equal(n.B.ballsFor,2);assert.equal(n.A.runsFor,10);assert.equal(nrrContribution(make('Test')),null);let d=open(make());d=command(d,{command:'close'});d=command(d,{command:'target',target:5,maxBalls:12,method:'DLS',calculationReference:'Synthetic approved vector',note:'Rain'});d=open(d);d=command(d,{runs:6,boundary:6});n=nrrContribution(d);assert.equal(n.A.runsFor,4);assert.equal(n.A.ballsFor,12);assert.equal(standings([{...d,id:'d'}, {...d,id:'d'}])[0].played,1);});
test('plans produce unique round robins, knockout byes, IPL dependencies and group stages',()=>{const teams=['A','B','C','D'];assert.equal(tournamentPlan(teams).fixtures.length,6);assert.equal(tournamentPlan(teams,'Double round-robin').fixtures.length,12);assert.equal(tournamentPlan(teams,'IPL playoffs').fixtures.at(-1).teamB,'winner:Q2');assert.equal(tournamentPlan(['A','B','C'],'Knockout').fixtures.length,3);assert.equal(tournamentPlan(teams,'Groups + Super stage').fixtures.length,2);assert.equal(tournamentPlan(['A','B','C'],'Swiss').fixtures.filter(f=>f.bye).length,1);});
