import test from 'node:test';
import assert from 'node:assert/strict';
import {appendCommand,calculateMatch} from '../public/scoring-engine.js';
import {deliveryMoments,createMomentTracker} from '../public/score-moments.js';
import {scorer} from '../public/score-studio.js';
function match(){let m={id:'unit-test',name:'Test fixture only',proScoring:true,teamA:'Test A',teamB:'Test B',overs:20,squads:{A:Array.from({length:11},(_,i)=>({id:'a'+i,name:'A '+i})),B:Array.from({length:11},(_,i)=>({id:'b'+i,name:'B '+i}))},scoringConfig:{maxBowlerOvers:4},events:[]};return appendCommand(m,{command:'select',strikerId:'a0',nonStrikerId:'a1',bowlerId:'b0'})}
test('boundaries use boundary attribution, not total delivery runs',()=>{const m=match();for(const runs of [4,6]){const next=appendCommand(m,{runs,boundary:runs});assert.ok(deliveryMoments(m,next).some(x=>x.kind===(runs===4?'four':'six')))}assert.equal(deliveryMoments(m,appendCommand(m,{runs:4})).length,0);const next=appendCommand(m,{runs:4,boundary:4,runType:'bye'});assert.equal(deliveryMoments(m,next)[0].detail,'Four byes')});
test('duck is annotation for actual dismissed batter, never a bowler wicket for a runout',()=>{const m=match(),next=appendCommand(m,{dismissal:'run_out',outId:'a1',changeEnds:false});assert.ok(deliveryMoments(m,next).some(x=>x.kind==='duck'&&x.detail.includes('A 1')));assert.ok(!deliveryMoments(m,next).some(x=>x.kind==='hattrick'));assert.equal(calculateMatch(next).first.bowlers.b0.wickets,0)});
test('three consecutive legal credited wickets detect once; runouts interrupt streak',()=>{
 let m=match(),last=[];for(let i=0;i<3;i++){if(i)m=appendCommand(m,{command:'select',strikerId:'a'+(i+1),nonStrikerId:'a1',bowlerId:'b0'});const next=appendCommand(m,{dismissal:'bowled'});last=deliveryMoments(m,next);m=next;if(i<2)assert.ok(!last.some(x=>x.kind==='hattrick'))}assert.ok(last.some(x=>x.kind==='hattrick'));
 const events=m.events.map(e=>e.eventType==='delivery'&&e.outId==='a2'?{...e,dismissal:'run_out'}:e);assert.ok(!deliveryMoments({...m,events:events.slice(0,-1)},{...m,events}).some(x=>x.kind==='hattrick'));
});
test('initial load, polling, undo, edits, catch-up and match switching do not replay events',()=>{const m=match(),next=appendCommand(m,{runs:6,boundary:6}),tracker=createMomentTracker();assert.deepEqual(tracker.observe(m),[]);assert.ok(tracker.observe(next).length);assert.deepEqual(tracker.observe(next),[]);assert.deepEqual(tracker.observe(m),[]);assert.equal(tracker.corrected,true);assert.deepEqual(tracker.observe(next),[]);tracker.reset();assert.deepEqual(tracker.observe(next),[]);assert.deepEqual(deliveryMoments(m,{...next,id:'other'}),[]);assert.deepEqual(deliveryMoments(m,appendCommand(next,{runs:4,boundary:4})),[]);assert.deepEqual(deliveryMoments(next,{...next,events:next.events.map((e,i)=>i===1?{...e,runs:4,batRuns:4,boundary:4}:e)}),[])});
test('milestones crossing thresholds, free hits and maiden overs derive from ledger',()=>{let m=match();for(let i=0;i<5;i++)m=appendCommand(m,{runs:0});const next=appendCommand(m,{runs:0});assert.ok(deliveryMoments(m,next).some(x=>x.kind==='maiden'));const start=match(),nb=appendCommand(start,{runs:0,noBall:true});assert.ok(deliveryMoments(start,nb).some(x=>x.kind==='freehit'));let runs=match();runs=appendCommand(runs,{runs:30});runs=appendCommand(runs,{runs:18});assert.ok(deliveryMoments(runs,appendCommand(runs,{runs:4,boundary:4})).some(x=>x.title==='50 RUNS'));});
test('console keeps original scoring controls and escapes names',()=>{const m=match();m.name='<img src=x onerror=bad>';const html=scorer(m,{own:()=>true});assert.match(html,/future-score/);assert.match(html,/SCORER COMMAND DECK/);assert.match(html,/data-cricket="quick"/);assert.match(html,/data-cricket="undo"/);assert.match(html,/&lt;img/);assert.ok(!html.includes('<img src=x'));});
