import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handle} from '../server/api.js';
function fixture(){const sqlite=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));const DB={prepare(sql){const statement=sqlite.prepare(sql);return {args:[],bind(...args){this.args=args;return this},async all(){return {results:statement.all(...this.args)}},async first(){return statement.get(...this.args)||null},async run(){const r=statement.run(...this.args);return {meta:{changes:Number(r.changes)}}}}},async batch(queries){sqlite.exec('BEGIN');try{const result=[];for(const q of queries)result.push(await q.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};return {DB}}
async function call(env,path,method='GET',body,user='alice',origin){if(user&&!env.skipAutoProfile&&!['account','status'].includes(path.split('/')[0])){const row=await env.DB.prepare('SELECT data FROM accounts WHERE owner=?').bind(user).first(),old=row?JSON.parse(row.data):{};const p={name:'Synthetic member',city:'Test city',country:'US',roles:['player'],primaryRole:'player',...old,consent:{termsAccepted:true,privacyAccepted:true,policyVersion:'2026-10-08',acceptedAt:'2026-10-08T00:00:00Z'}};if(!row)await env.DB.prepare('INSERT OR IGNORE INTO accounts(owner,email,data,created,updated) VALUES(?,?,?,?,?)').bind(user,user+'@example.test',JSON.stringify(p),'test','test').run();else await env.DB.prepare('UPDATE accounts SET data=? WHERE owner=?').bind(JSON.stringify(p),user).run();}const headers={'Content-Type':'application/json'};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test';}if(origin)headers.origin=origin;const r=await handle(new Request('https://cricket.test/api/'+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),env);return {status:r.status,data:await r.json()}}
async function create(env,type,data,user='alice'){const r=await call(env,'records','POST',{type,data},user);assert.equal(r.status,201,JSON.stringify(r.data));return r.data.id}
import {readJson,validateJson,checkRequest,blockedPath,secureResponse,rateLimit} from '../server/security.js';
import {admin} from '../server/payments.js';
test('API requires complete trusted identity and anonymous status does not reflect identity headers',async()=>{const env=fixture();const r=await handle(new Request('https://cricket.test/api/data',{headers:{'oai-authenticated-user-id':'alice'}}),env);assert.equal(r.status,401);const status=await handle(new Request('https://cricket.test/api/status',{headers:{'oai-authenticated-user-full-name':'Someone','oai-authenticated-user-email':'someone@example.test'}}),env);assert.equal((await status.json()).name,null);});
test('administrator can be pinned to subject and email; self-declared roles do not grant access',async()=>{const env=fixture();env.PLATFORM_ADMIN_EMAIL='admin@example.test';env.PLATFORM_ADMIN_USER_ID='admin';env.PLATFORM_ADMIN_USER_ID='trusted-admin';assert.equal(admin(new Request('https://cricket.test',{headers:{'oai-authenticated-user-email':'admin@example.test'}}),env),false);assert.equal(admin(new Request('https://cricket.test',{headers:{'oai-authenticated-user-id':'attacker','oai-authenticated-user-email':'admin@example.test'}}),env),false);assert.equal(admin(new Request('https://cricket.test',{headers:{'oai-authenticated-user-id':'trusted-admin','oai-authenticated-user-email':'admin@example.test'}}),env),true);});
test('CSRF rejects cross-origin, same-site sibling and missing verification on cookie-authenticated writes',()=>{for(const h of [{'Origin':'https://evil.test'},{'Sec-Fetch-Site':'cross-site'},{'Sec-Fetch-Site':'same-site'},{Cookie:'session=synthetic'}])assert.throws(()=>checkRequest(new Request('https://cricket.test/api/account',{method:'POST',headers:h})),/origin|verification/);assert.doesNotThrow(()=>checkRequest(new Request('https://cricket.test/api/account',{method:'POST',headers:{Origin:'https://cricket.test'}})));assert.throws(()=>checkRequest(new Request('https://cricket.test/api/account',{method:'TRACE'})));});
test('streamed request byte limit applies without Content-Length; invalid UTF8, media type and prototype keys fail closed',async()=>{await assert.rejects(readJson(new Request('https://cricket.test',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})),e=>e.status===415);const stream=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('{"text":"'+'x'.repeat(30000)+'"}'));c.close();}});await assert.rejects(readJson(new Request('https://cricket.test',{method:'POST',headers:{'Content-Type':'application/json'},body:stream,duplex:'half'})),e=>e.status===413);await assert.rejects(readJson(new Request('https://cricket.test',{method:'POST',headers:{'Content-Type':'application/json'},body:new Uint8Array([255,254])})),e=>e.status===400);assert.throws(()=>validateJson(JSON.parse('{"__proto__":{"polluted":true}}')));assert.throws(()=>validateJson({n:Infinity}));assert.throws(()=>validateJson({x:Array(501).fill('x')}));assert.throws(()=>validateJson({x:'\0'}));assert.deepEqual(validateJson({name:'Nuhan',roles:['player']}),{name:'Nuhan',roles:['player']});});
test('rate limits reserve atomically across concurrent calls and isolate identities and scopes',async()=>{const env=fixture();const xs=await Promise.allSettled(Array.from({length:15},()=>rateLimit(env.DB,'alice','isolated',10,3600)));assert.equal(xs.filter(x=>x.status==='fulfilled').length,10);assert.equal(xs.filter(x=>x.status==='rejected'&&x.reason.status===429).length,5);await rateLimit(env.DB,'bob','isolated',10,3600);await rateLimit(env.DB,'alice','another',10,3600);const rows=(await env.DB.prepare('SELECT key FROM api_rate_limits').all()).results;assert.ok(rows.every(r=>!r.key.includes('alice')&&!r.key.includes('bob')));});
test('API abuse returns 429 and Retry-After before another record is created',async()=>{const env=fixture();await call(env,'data');for(let i=0;i<40;i++){const r=await call(env,'records','POST',{type:'players',data:{name:'Synthetic '+i}});assert.equal(r.status,201);}const r=await handle(new Request('https://cricket.test/api/records',{method:'POST',headers:{'Content-Type':'application/json','oai-authenticated-user-id':'alice','oai-authenticated-user-email':'alice@example.test'},body:JSON.stringify({type:'players',data:{name:'Exceeded'}})}),env);assert.equal(r.status,429);assert.ok(Number(r.headers.get('Retry-After'))>0);assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM records').first()).n,40);});
test('source/config paths are blocked after encoding, while real features and well-known paths survive',()=>{for(const p of ['/.env','/.git/config','/%252eenv','/server/payments.js','/db/schema.ts','/drizzle/0019.sql','/package-lock.json','/assets/app.js.map','/foo\\.env'])assert.equal(blockedPath(p),true,p);for(const p of ['/carpool','/expenses','/api/account','/app.js','/.well-known/security.txt'])assert.equal(blockedPath(p),false,p);});
test('security response keeps attachment metadata, disables storage and restricts executable content with a nonce',async()=>{const r=secureResponse(new Response('ok',{headers:{'Content-Type':'text/html','X-Powered-By':'test'}}),new Request('https://cricket.test/'),'syntheticNonce');assert.equal(r.headers.get('X-Powered-By'),null);assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.equal(r.headers.get('Cache-Control'),'private, no-store');assert.match(r.headers.get('Content-Security-Policy'),/nonce-syntheticNonce/);assert.match(r.headers.get('Content-Security-Policy'),/script-src-attr 'none'/);assert.match(r.headers.get('Content-Security-Policy'),/object-src 'none'/);assert.match(r.headers.get('Strict-Transport-Security'),/31536000/);const head=secureResponse(new Response('x',{headers:{'Content-Disposition':'attachment'}}),new Request('https://cricket.test/api/assets/a',{method:'HEAD'}));assert.equal(await head.text(),'');assert.equal(head.headers.get('Content-Disposition'),'attachment');});
test('private reports and applications do not appear in another member’s global action feed',async()=>{const env=fixture(),id=await create(env,'recruitment',{name:'Synthetic team vacancy'});assert.equal((await call(env,'action/'+id,'POST',{kind:'apply'},'bob')).status,201);assert.equal((await call(env,'data','GET',undefined,'carol')).data.actions.some(x=>x.kind==='apply'),false);assert.equal((await call(env,'data')).data.actions.some(x=>x.kind==='apply'),true);});
